config/express.js
See issue #318 for details on changes.  Closes #318.
=> move helmet and express.static before sessions for performance

config/config.js, modules/core/server/views/layout.server.view.html
This fixes https://groups.google.com/forum/#!msg/meanjs/qOPHzMtWrPY/da9puKbyI5UJ as suggested by Silla Tan - also mentioned in #283 which was closed without a fix.
=> Fix #283 & #321 path issues [+1 for Windows]

.gitignore
settings for cloud9 ide added to gitignore
=> settings for cloud9 ide added to gitignore

app/controllers/users/users.authorization.server.controller.js
Better use of syntactic sugar.
=> User ID middleware now uses .findById

public/modules/users/services/authentication.client.service.js
Added the $window, no need of _this.
=> Auth service

scripts/generate-ssl-certs.sh
=> Fixing typo in scripts/generate-ssl-certs.sh

config/lib/express.js, config/lib/socket.io.js, package.json
@lirantal I tested it and sessions still work, but let me know if you have any issues with it.
=> Update connect-mongo to support Mongoose 4.0.0

config/lib/express.js
I think it's good to have these here "just in case", even the seed project wouldn't have any fonts/svgs. These are just so common filetypes at any project.
Thoughts?
=> Add fonts and svgs to gzip compression pattern

modules/users/server/controllers/users/users.authorization.server.controller.js
Looks like these aren't needed now that we have ACL.
=> Remove un-used hasAuthorization and requiresLogin

.gitignore, config/config.js, config/env/local.example.js, gruntfile.js, package.json
@see same PR merged in 'master' branch: https://github.com/meanjs/mean/pull/557/files
this one is a PR to port it to 0.4.0 branch
=> porting pull request from master to 0.4.0 branch: Local environment ariables to address issue #553 #557

.gitignore
- remove access.log (*.log is enough)
- Move local.js config under MEAN.JS
- Rename iOS/Apple => OS (this is a mix of windows/osx stuff anyways)
=> Sorting out .gitignore

config/env/production.js
Fix the indentation in config.
=> formatting: indent

docs.html
=> Swap URL and Type in Docs

modules/users/server/models/user.server.model.js, package.json
Rely on https://github.com/chriso/validator.js for validations.
=> Use validator.js for email and password length validation.

config/lib/express.js
Addresses issue reported in https://github.com/meanjs/mean/issues/694
=> Removing unused passport variable in express.js library file

config/config.js
Addressing issue https://github.com/meanjs/mean/issues/702
=> fixing chalk and console usage for consistency reasons

modules/chat/client/controllers/chat.client.controller.js, modules/core/client/services/socket.io.client.service.js
Updated the Socket client service, with a connect() method. Moved state
redirect out of from Socket service.  Added the Authentication.user
check to the Chat client controller, and added a check to make sure the
Socket client service is connected to the server; if not, then connect
using the new connect() method.
I'm just putting this up here, since I think the Socket client service could be refactored. There is a loose relation to #686, and perhaps #482.
=> Socket IO client enhancement with connect() method

config/env/default.js, config/env/development.js, config/lib/express.js, modules/core/server/views/layout.server.view.html
Redo of Pull #664 (was having git issues)
=> Move livereload, image, and favicon to config

modules/chat/client/controllers/chat.client.controller.js
During my last PR merge, the dependency injection for Authentication and
$location weren't merged properly. I added them back to the Chat client
controller.
=> Added missing dependency injection in Chat

.gitignore, bower.json, modules/articles/tests/client/articles.client.controller.tests.js, modules/chat/tests/client/chat.client.controller.tests.js, modules/core/client/services/menus.client.service.js, modules/core/tests/client/header.client.controller.tests.js, modules/core/tests/client/menus.client.service.tests.js, modules/core/tests/client/socket.io.client.service.tests.js, modules/users/server/controllers/admin.server.controller.js, modules/users/server/controllers/users/users.authorization.server.controller.js, modules/users/server/policies/admin.server.policy.js, modules/users/server/routes/admin.server.routes.js, modules/users/server/routes/users.server.routes.js, modules/users/tests/client/authentication.client.controller.tests.js, modules/users/tests/client/password.client.controller.tests.js, modules/users/tests/server/user.server.routes.tests.js
Fixes #663.
* Adding __coverage/__ to .gitignore
* Adding client test coverage for:
* Articles controller
* Chat controller
* Menus service
* Header controller
* Password controller
* Authentication controller
* Small changes on Menu service
* Tabs changed to 2 spaces
* Removed [unreachable line](https://github.com/meanjs/mean/pull/728/files#diff-1e5dbd4f8e8c78fcdf6081de540f09d1L46)
* Fixing [typeo](https://github.com/meanjs/mean/pull/728/files#diff-1e5dbd4f8e8c78fcdf6081de540f09d1L40) on error message.
=> Adding client side test coverage.

config/env/development.js, config/env/test.js
=> Get site title from default

config/lib/app.js, config/lib/mongoose.js, gruntfile.js, server.js
Refactoring server application service to enable modularity and callbacks, as well as provide app, db, config variables outside of server.js
* Note: this isn't just a general refactoring for the fun of it, it's required to be able to integrate better the tests and the code coverage, but I didn't yet finish working on those so this at least lays the foundation so I can have more time to prepare them in a later PR.
=> Refactoring server application service

README.md
updating the new 0.4.1 dev branch for when 0.4.0 will actually be released
=> Updating README with reference to new development branch

README.md
updating gh-pages README with more elaborate documentation information on how to get running
=> README update for gh-pages

.gitignore
@lirantal Another .gitignore to make it easy to switch back and forth
=> Make it easier for switching between branches

config/lib/express.js, config/lib/socket.io.js, scripts/generate-ssl-certs.sh
Adding ordered cipher list, stronger settings in generate-ssl-certs script, and hsts settings
=> Adding more secure settings

config/env/default.js, config/lib/express.js
Addresses issue raised here #802
=> Adding support for configurable session expiration time

modules/users/client/views/admin/user-edit.client.view.html
Fixed end tags in the page header of the user edit page
=> Fixed end tags in the page header of the user edit page

config/config.js, config/env/production.js, config/lib/express.js, config/lib/socket.io.js
adding support for a configurable ssl-mode and and ssl cert/key files in the environment configuration
=> Configurable SSL mode options

.editorconfig
@trainerbill This should fix your issue.
=> Changed .html files to have 2 spaces instead of tabs

config/env/default.js
Added the missing /client/ path to the favicon & logo in the default env
config.
=> [hotfix] Added missing /client/ path

modules/users/server/templates/reset-password-confirm-email.server.view.html, modules/users/server/templates/reset-password-email.server.view.html
=> Correct <br /> Tags and set Title

modules/chat/client/views/chat.client.view.html
This is something that has been bothering me for a while...
Disables the submit button on the Chat form, when no message is present.
Also, removed the `data-` prefix from the various Chat view elements.
=> [fix] Empty Chat Messages

Dockerfile
Same as #789 but squashed too one commit. 
@liuhill If you want to squash yours and get yours merged in, go for it! I'm just trying to get a handful of these bug fixes merged in.
=> [fix] Install ruby and SASS with Docker [Closes #789]

config/env/default.js, config/lib/express.js
Refactoring the Session Cookie configuration and adding more configurable parameters
=> Session Cookie Configuration enhancements

.travis.yml
Adding the NSP tool to audit our packages version for known security vulnerabilities as part of the CI process
=> Security check as part of our CI

.travis.yml
@lirantal I added this snippet to add Travis notifications in Gitter. Hopefully we'll make Gitter more informative by doing things like this.
=> Travis notifications in Gitter

bower.json, config/assets/default.js, modules/articles/tests/server/article.server.model.tests.js, modules/articles/tests/server/article.server.routes.tests.js, modules/users/client/controllers/authentication.client.controller.js, modules/users/client/controllers/password.client.controller.js, modules/users/client/controllers/settings/change-password.client.controller.js, modules/users/client/directives/password-validator.client.directive.js, modules/users/client/directives/password-verify.client.directive.js, modules/users/client/services/password-validator.client.service.js, modules/users/client/views/authentication/signup.client.view.html, modules/users/client/views/password/forgot-password.client.view.html, modules/users/client/views/password/reset-password.client.view.html, modules/users/client/views/settings/change-password.client.view.html, modules/users/client/views/settings/edit-profile.client.view.html, modules/users/server/models/user.server.model.js, modules/users/tests/client/password.client.controller.tests.js, modules/users/tests/server/user.server.model.tests.js, modules/users/tests/server/user.server.routes.tests.js, package.json
Adding stronger password requirements for improving security based on OWASP. Fixing #848
=> Adding stronger password security

_includes/docs/0.3.x/angularjstests.html
Typos
Capitalized K in Karma in several places, as per its official docs
Updated Angular testing links from 404s
Pointed a link to main Karma docs instead of a versioned page
=> Fixed typos, broken links

modules/users/tests/server/user.server.routes.tests.js
The commits are straightforward.
=> Updating comments for tests in code

modules/users/server/controllers/users/users.password.server.controller.js
Closes #923 - making password reset links work for both http and https configuration.
=> Fixed #923 - password reset links SSL support

README.md
Link for the node js download is mismatching.
=> Link for download link (NodeJs download)

modules/core/tests/server/core.server.config.tests.js
adding `return` to `done()` in tests mentioned in comments of #927
=> Adding return done() to tests

CONTRIBUTING.md, README.md
Supersedes #998. 
@lirantal I made your suggested changes from the previous PR.
=> [docs] Information about Contributing

gruntfile.js, gulpfile.js, scripts/reset-password.js
Fixing jshint issues with grunt, gulp, and reset-password script.
=> Fixing jshint issues with grunt, gulp, and reset-password script.

_includes/docs/0.4.x/gettingstarted.html
=> docs: Minor Updates to Getting Started

_includes/css/common.css, _includes/docs/0.4.x/angularMenus.html, _includes/docs/0.4.x/index.html
Same as #809 but with the requested changes. The other PR has been sitting open for over 2 months waiting on changes, so I'm submitting this one to get them merged in.
Credit: @cdriscol
=> docs: Add Angular Service Docs [Closes #809]

.gitignore
=> feat: Add Additionl Log Paths to GitIgnore

Dockerfile
=> bug(docker): Change Node Version

README.md
Updating the readme.md to clarify what the yo generator currently does.
=> Update readme for mean.js 0.4.x

config/lib/express.js
=> fix(core): Serve static files without session init

modules/users/server/controllers/users/users.authentication.server.controller.js, modules/users/server/controllers/users/users.password.server.controller.js, modules/users/server/controllers/users/users.profile.server.controller.js
Removing redundant variables defined and not used
=> fix(users): Removing redundant variables

modules/articles/server/controllers/articles.server.controller.js, modules/articles/server/models/article.server.model.js, modules/articles/server/policies/articles.server.policy.js, modules/articles/server/routes/articles.server.routes.js, modules/core/client/core.client.module.js, modules/users/client/config/users-admin.client.menus.js, modules/users/client/controllers/password.client.controller.js, modules/users/client/users.client.module.js, modules/users/server/config/strategies/facebook.js, modules/users/server/config/strategies/github.js, modules/users/server/config/strategies/google.js, modules/users/server/config/strategies/linkedin.js, modules/users/server/config/strategies/local.js, modules/users/server/config/strategies/paypal.js, modules/users/server/config/strategies/twitter.js, modules/users/server/config/users.server.config.js, modules/users/server/controllers/admin.server.controller.js, modules/users/server/controllers/users.server.controller.js, modules/users/server/controllers/users/users.authentication.server.controller.js, modules/users/server/controllers/users/users.authorization.server.controller.js, modules/users/server/controllers/users/users.password.server.controller.js, modules/users/server/controllers/users/users.profile.server.controller.js, modules/users/server/models/user.server.model.js, modules/users/server/policies/admin.server.policy.js, modules/users/server/routes/admin.server.routes.js, modules/users/server/routes/auth.server.routes.js
Changed some bad comments referencing the Articles module in other modules.
Typo fixed in xxx.client.modules.js files ("Application" => "Applicaion")
Full stop character removed at the end of line comments
=> fix(docs): Fix comments content and style

config/lib/app.js
Adding host information to the log initialization and aligning the
texts.
=> fix(core): Adding server info to log initialization

bower.json
Aphabetize the bower dependencies so it doesn't break PR's when you bower --save
=> fix(bower): Alphabetize list

package.json
@vaucouleur Nope. There was no reason for me to leave it as a carrot. It was accidentally missed, my apologies. Thanks for pointing it out!
=> feat(package.json): Set Async version to ~ from ^

modules/users/client/services/password-validator.client.service.js
=> fix(users): Correct spelling/grammar mistakes

config/lib/logger.js, modules/users/client/directives/users.client.directive.js
Remove byte-order mark from source files.
Fixes #1227
=> fix(build): Remove BOM

package.json
Change the version to 0.5.0-beta so people know that this is beta code and things are rapidly changing.
=> doc(package): Change meanjs version to 0.5.0-beta

PULL_REQUEST_TEMPLATE.md
=> feat(github): adding support for Pull Requests templates

README.md
Removed a duplicate line where a duplicate mention of installing grunt was placed.
=> Docs(readme): Removed duplicate mention of installing grunt

modules/core/client/css/core.css, modules/core/server/views/layout.server.view.html
Enhancement(core): Relative position attribute added to the header.
Relative position attribute added to the header. proposed by @generalgmt
Fixes #1275
=> Enhancement(core):Relative position attribute added to the header.

Dockerfile
* Setting the maintainer information to MEAN.JS team as well as in the comments
* Adding a docker-compose clause
=> fix(docker): updating maintainer and docker compose

Dockerfile
More efficient dockerfile for building the image only when changes are strictly made to one of packages.json or bower.json
=> Updating Dockerfile for more efficient image building

README.md
Add git to prerequisites so that especially Windows users would realise to install it.
Fixes #1310
=> fix(docs): Add git to Prerequisites

modules/core/client/services/menu.client.service.js, modules/core/tests/client/menus.client.service.tests.js
fixed typo in modules/core/client/services/menu.client.service.js
Fixes #1354
=> fix(core): Typo in menu.client.service.js

PULL_REQUEST_TEMPLATE.md
Line 18 change "like like" to "look like"
Line 38 fixed a typo in "reference"
Fixed #1370
=> We fixed a typo

README.md
=> Improving README file

modules/core/server/views/layout.server.view.html
=> feat(core): Enable ng-strict-di

modules/core/client/directives/page-title.client.directive.js
fix Eslint throws "Move the invocation into the parens that contain the function wrap-iife"
fix typo: retrict -> restrict
=> fix(core): fix page-title directive

modules/core/server/controllers/errors.server.controller.js, modules/users/server/controllers/users/users.profile.server.controller.js
fix(user): fix changeProfilePicture
* use promises to simplify callbacks
* use fs.unlink to delete old picture once the profile is updated
Fixes #1415
=> fix(user): fix changeProfilePicture

modules/core/server/views/layout.server.view.html
feat(core): Add noscript tag to layout
See #1397 
It's true that not many users block JavaScript these days, but it's certainly 
nice (and costs nothing) to confront those users with a friendly message 
rather than just a blank screen.
=> Added noscript tag to layout

config/env/production.js, package.json
Support for mongodb secure connections with ssl certificates
Fixes #1349
=> Support for mongodb secure connections with ssl certificates

.travis.yml
The `nsp` command has been updated and the `.travis.yml` file needs an update in this direction as well.
=> nsp command needs update in the build process

modules/users/tests/server/user.server.routes.tests.js
Clean out commented `.send()` from user CRUD test.
=> fix(user): Clean out `.send()` from tests

gulpfile.js, scripts/upgrade-users-sparse-index.js
=> Tidying up minor lint and layout issues

modules/articles/client/controllers/admin/article.client.controller.js
fix(article): add callback for remove article
Add callback on remove article for state transition
Fixes #1274
=> fix(article): add callback for remove article

Dockerfile-production
Equals to #1494 but in production.
=> deploy(docker) fix(docker) - Updated Dockerfile production

config/assets/cloud-foundry.js, package.json
=> bluemix(remove): Remove Excess CF files

modules/articles/client/services/articles.client.service.js, modules/core/client/app/init.js, modules/users/server/controllers/users/users.password.server.controller.js
logs with $log in client idea proposed by @simison
also removed unnecessary consoles in [users.password.server.controller.js](https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.password.server.controller.js)
Fixes #1541
=> feat(core): change console in angular to

modules/users/tests/server/user.server.routes.tests.js
Remove credentials from change-profile-picture request body.
=> Fix(Users): Remove redundant request body

bower.json, config/assets/default.js, config/assets/production.js, modules/articles/client/controllers/admin/article.client.controller.js, modules/articles/client/controllers/articles.client.controller.js, modules/articles/client/views/admin/form-article.client.view.html, modules/articles/tests/client/admin.articles.client.controller.tests.js, modules/core/client/app/config.js, modules/users/client/controllers/admin/user.client.controller.js, modules/users/client/controllers/authentication.client.controller.js, modules/users/client/controllers/password.client.controller.js, modules/users/client/controllers/settings/change-password.client.controller.js, modules/users/client/controllers/settings/change-profile-picture.client.controller.js, modules/users/client/controllers/settings/edit-profile.client.controller.js, modules/users/client/controllers/settings/manage-social-accounts.client.controller.js, modules/users/client/views/admin/edit-user.client.view.html, modules/users/client/views/authentication/signup.client.view.html, modules/users/client/views/password/forgot-password.client.view.html, modules/users/client/views/password/reset-password.client.view.html, modules/users/client/views/settings/change-password.client.view.html, modules/users/client/views/settings/change-profile-picture.client.view.html, modules/users/client/views/settings/edit-profile.client.view.html, modules/users/tests/client/authentication.client.controller.tests.js, modules/users/tests/client/edit-profile.client.controller.tests.js, modules/users/tests/client/password.client.controller.tests.js, modules/users/tests/e2e/users.e2e.tests.js
feat(core): add notification feedback with angular-ui-notification
Added visual notification for user/article updates
angular-ui-notification config added to core client config
Notification idea from #369
=> feat(core): add notification feedback with angular-ui-notification

config/config.js
fix(config): config.app.domain -> config.domain
Issue brought up by @19r3ka
Fixes #1506
=> fix(config): config.app.domain -> config.domain

.travis.yml
Adding snyk support to test our dependencies for insecure vulnerabilities as part of our build process
=> snyk support in CI/CD

README.md
Added the Snyk vulnerabilities badge to `README.md`
=> doc(readme): wear the Snyk badge with pride!

modules/users/tests/e2e/users.e2e.tests.js, modules/users/tests/server/user.server.routes.tests.js
Fixes https://github.com/meanjs/mean/commit/6a6b630292cb2e05d1d79c9bf233d23955e2ae17
=> fix(users): test for usernameOrEmail

CONTRIBUTING.md
Updating instructions on how to generate the changelog for releases
=> Updating release instructions

modules/articles/client/views/admin/form-article.client.view.html, modules/core/client/directives/auto-focus.client.directive.js, modules/users/client/views/admin/edit-user.client.view.html, modules/users/client/views/password/forgot-password.client.view.html, modules/users/client/views/password/reset-password.client.view.html, modules/users/client/views/settings/change-password.client.view.html
feat(core): Better autofocus
Further to https://github.com/meanjs/mean/pull/1499, this improves the autofocus directive by adding it to more default input fields across MEAN and also setting the cursor to jump to the end of the input field rather than the beginning.
=> feat(core): Better autofocus

.travis.yml, gulpfile.js, package.json, scripts/setup-protractor.sh
=> fix(protractor): updating gulp-protractor

modules/users/server/controllers/users/users.authentication.server.controller.js
Fixes an issue where a provider account could be added to the logged in
user's additionalProviderData, when another user has already connected
that same account.
Refactors the saveOAuthUserProfile method to consider the results of the
provider search query, whether or not the current user is logged in.
Steps to reproduce:
1. Signup for a new MEANJS account using a social provider account.
2. Signup for a new MEANJS account using local provider.
3. While still logged in with the User created in step 2, add the same social provider account used in step 1.
Results will be that the local provider User will be connected to the social provider account that was created in step 1.
=> fix(users): Duplicate Provider Accounts

modules/articles/tests/server/admin.article.server.routes.tests.js, modules/articles/tests/server/article.server.model.tests.js, modules/articles/tests/server/article.server.routes.tests.js
Promisifies object creation in beforeEach and afterEach hooks in article server tests.
Fixes #1773
=> feat(articles): Promisifies article server test set up and clean up

package.json
Trying the PR again in place of #1755 with a rebase to see if the tests pass. 
Resolves #1755
=> fix(dependencies): upgrading nodemailer

modules/users/server/controllers/users/users.password.server.controller.js
Fixes an incorrect reference to the application's Domain configuration
setting.
=> fix(users): Domain config setting

modules/core/client/services/menu.client.service.js
The `for loops`, especially the nested `for loops`, over array elements with variable names containing `index` made the code incomprehensible.
=> refactor(menus): Refactor to the Menus client service to use functional loops/filters

.travis.yml
Fix this issue : Chromedriver error “Chrome version must be >= 63..”
=> fix(travis) : chrome install 

package.json
```
Header
Blank Line
Body
Blank Line
Footer
The header should look like:
<type>(<scope>): <subject>
The body should have any necessary detailed info about the commit:
An example, references as to where this idea came from, etc.
The footer should have all the issues tagged:
Fixes #123, Fixes #456
So a commit should look like:
feat(users): Add new Yahoo authentication
Yahoo authentication idea proposed by @codydaig
Example implementation in file.js
Fixes #82
```
* Types: 
* feat - Features, Enhancements, and overall Improvements
* fix - Fixes, Bugs, HotFixs, etc...
* doc - Changes to the Documentation and doesn't actually touch any code.
* Scope:
* The scope should be where the change took place.
* Examples: users, core, config, articles
* Subject:
* The subject line should be clear and …
=> feat(core): Update supported node.js and npm versions
