meanjs/mean

config/express.js

replacing old expressjs 3.x built-in 'compress' middleware with standalone compression middleware

Aligning ExpressJS 4.0 compatibility

---

app/views/layout.server.view.html

cleaning up css and js assets so they look indented and easy to read on browsers when viewing the HTML source of the page
before:
after:

cleaning up css and js assets 

---

README.md
gruntfile.js

Adds two more tasks to execute server and client tests separately
To run full suite
grunt test
To run only server tests
grunt test:server
To run only client tests
grunt test:client
Fixes https://github.com/meanjs/mean/issues/155

Adds support for re-running server and client tests automatically

---

config/strategies/github.js
config/strategies/twitter.js

I think `firstName` and `lastName` should be set when signing through providers. This fixes it for github and twitter.

Infer first and last name from github and twitter response

---

modules/users/server/config/strategies/facebook.js

Username is now deprecated on Facebook API 2.0, as discussed in #280

Remove username from facebook strategy

---

modules/users/server/config/strategies/facebook.js
modules/users/server/config/strategies/twitter.js

@ilanbiala please, let me know where I should be suggesting these PRs. Shall I do it for 0.4.0, master or both?
Regarding image sizes, I just faced a need for larger dimensions, so I changed the profileImageUrl for FB and Twitter. Thought perhaps this should be the default. What do you think?

Adjust profile image dimensions for Fb and Twitter

---

config/assets/default.js

Fix issue #424

---

app/controllers/articles.server.controller.js
app/controllers/users/users.password.server.controller.js
app/tests/article.server.model.test.js
app/tests/article.server.routes.test.js
app/views/layout.server.view.html
config/env/all.js
public/modules/articles/controllers/articles.client.controller.js
public/modules/articles/tests/articles.client.controller.test.js

Fixes https://github.com/meanjs/mean/issues/441

Removes unnecessary whitespace, formats code and add comments

---

package.json

node-sass < 2.0 which gulp-sass depends upon can't be installed on node-0.12 so doing an npm install gave weird errors.

update gulp-sass to ensure node-0.12 compatibility

---

modules/users/server/models/user.server.model.js

**This pull request merges the fix proposed in [pull/253](https://github.com/meanjs/mean/pull/253) into the 0.4.0 branch.**
The user password salt should be encoded with Base64 before being saved
to the database.
The current code adds an unecessary step of converting the result of
crypto.randomBytes() (which already returns a SlowBuffer) to a Base64
string and back again to a Buffer, and misses the final step of
converting the Buffer's bytes back to a Base64 string.
Because of this, the salt stored in the database is garbled. This is
inconvenient when manipulating the data in a terminal or text editor.
When generating the password hash, the crypto.pbkdf2Sync() method
creates a new Buffer directly from the data supplied. Due to the
incorrect encoding of the salt, entropy is lost at this …

Correctly encode and decode password salt (0.4.0)

---

app/models/user.server.model.js

The user password salt should be encoded with Base64 before being saved
to the database.
The current code adds an unecessary step of converting the result of
crypto.randomBytes() (which already returns a SlowBuffer) to a Base64
string and back again to a Buffer, and misses the final step of
converting the Buffer's bytes back to a Base64 string.
Because of this, the salt stored in the database is garbled. This is
inconvenient when manipulating the data in a terminal or text editor.
When generating the password hash, the crypto.pbkdf2Sync() method
creates a new Buffer directly from the data supplied. Due to the
incorrect encoding of the salt, entropy is lost at this step,
weakening the security of stored passwords against brute force attacks.

Correctly encode and decode password salt

---

gulpfile.js

I updated the gulp build so that the mongoose connect/disconnect take place in the mocha task based on the lifecycle of the stream. This way, we can guarantee that the disconnect function is always called regardless of if the mocha tests fail or not. I'm also sending an error message to the task callback in the event that an error is generated by the tests. This way, gulp will finish in an error state if the tests fail and will finish in an ok state if they pass. I've tested this with passing and failing tests and the gulp build closes correctly now.

#450 Fix for hanging gulp on mongoose connections being left open

---

scripts/reset-password.js

I also added a scripts/ folder on 0.4.0, because we are missing one.

Reset password script

---

modules/core/server/views/layout.server.view.html

Headers were a weird mixture of html5 and xhtml. Now it's pure html5.
Use this as doctype if you really want it to be xhtml, but I don't see why would you want that with Angular:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

Fix headers to HTML5 format

---

modules/users/server/controllers/users/users.password.server.controller.js

Email address should not be shown to client

Hide email address

---

.gitignore
config/env/production.js
config/lib/express.js
config/lib/socket.io.js
generate-ssl-certs.sh
scripts/generate-ssl-certs.sh

adding ssl back in, moving scripts to script folder so we can ./script/gereratate-ssl-certs.sh

Adding ssl support back into 0.4.0

---

modules/users/server/config/strategies/local.js

This is implemented in master but it is not in 0.4.0.
This basically prevents username enumeration by providing the same error message when the username doesn't exist or when the username/password combination is wrong.

Add some abstraction to local strategy login error

---

modules/users/server/controllers/users/users.authentication.server.controller.js

>"Deprecated. Use either req.params, req.body or req.query, as applicable."
http://expressjs.com/api.html#req.param

Fix deprecated ExpressJS req.param('provider')

---

modules/core/client/views/header.client.view.html

Removing target on signin and signup anchors to prevent a complete page reload when changing to those states.

Remove targets on signin and signup anchors

---

config/env/production.js

Looks like this sneaked in during the merge with master. Not sure why it would be needed since we have the assets file.

Remove duplicate assets definition

---

modules/articles/tests/server/article.server.routes.tests.js

add return for done(err) in test

---

config/env/development.js

updated the development.js environment configuration file to use the mean-dev database instead of mean-test which is used for testing/stages environment

updated the development.js environment configuration to use mean-dev database

---

config/config.js
server.js

On starting up the server:
1. Remove the 'application started' suffix to the application title
2. Align the database name tab length
3. Remove the initial 'Application loaded using <NODENEV> environment' as it is anyway reported in the startup info.
Startup information after the fix:

cleaning up application startup information

---

README.md

updating README file with more elaborate instructions on running grunt in different environment modes (dev/prod/secure ssl)

Update README about grunt environment modes

---

modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js

Addresses issue: https://github.com/meanjs/mean/issues/295
updating the schema save pre hook so that it checks for a modified version of the password field before it tries to re-calculate the new password to save for the user model

Fixing user's passwords keep changing when saving the user model

---

modules/users/tests/server/user.server.model.tests.js

I just cloned the branch and both gulp and grunt fail on the lint task because of the missing semicolon.

JSHint test failing because of missing semicolon

---

README.md

1. Adding spaces between code blocks to text to make it more readable for raw text editors
2. Replacing 3 ticks (`) with just 1 for inline code block notation

cleaning up code blocks in README

---

scripts/generate-ssl-certs.sh

As a developer, I should not use SSL passwords for testing the production environment locally.

do not use aes when creating ssl certs to prevent password requirement

---

modules/core/tests/client/core.client.tests.js

appending a base tag to the head before jasmine tests run.

---

config/config.js

Fixes issue #660 
The _.merge properly merges two objects together. I'm not sure on the exact differences between _.extend and _.merge but they act differently, and _.merge produces the desired results.

change _.extend to _.merge

---

gruntfile.js

Enabling the lint task when running tests so we can identify coding convention issues on Pull-Requests in the CI
Addresses issue https://github.com/meanjs/mean/pull/645

Enable jshint on grunt test tasks

---

modules/articles/tests/server/article.server.routes.tests.js

There seems to be an extra console.log laying around in one of the Article Tests. Probably got left behind by someone during debugging.

Remove console.log from an article test

---

modules/core/server/controllers/errors.server.controller.js
modules/users/client/config/users.client.routes.js
modules/users/client/controllers/authentication.client.controller.js
modules/users/client/views/authentication/signin.client.view.html
modules/users/server/controllers/users/users.authentication.server.controller.js
modules/users/server/models/user.server.model.js

Emails are made unique. When user attempts to sign in through a provider in which his email is one that is already registered, user is redirected to the signin page with an error passed as a query string parameter.
Is this a reasonable solution to https://github.com/meanjs/mean/issues/118?
Your feedback is welcome. Thanks in advance.

Make emails unique

---

config/lib/express.js
modules/core/client/config/core.client.routes.js
modules/core/client/views/404.client.view.html
modules/core/server/controllers/core.server.controller.js
modules/core/server/routes/core.server.routes.js

- `/{api|modules|lib}/*` returns an error page when path doesn’t exist
(from Express).
- `/*` always returns index (from Express), but if `$state` doesn’t
exist, Angular redirects to `/not-found` (no 404 status in that case
though!)
- If `Accept: application/json` header is present without `Accept:
text/html`, return error as json. Hence looking at non existing /api/*
paths with browser would show html error, but querying them with script
would return json.
- Slightly prettier 404 error
Test:
```bash
curl http://localhost:3000/api/notfound -4 -H "Accept: application/json"
```
=> json error.
```bash
curl http://localhost:3000/api/notfound -4 -H "Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0
.8"
```
=> html error (imitates Chrome’s Accept header).
Starting …

#501 Handle 404 errors at Express backend and at Angular frontend

---

config/lib/express.js
modules/core/server/routes/core.server.routes.js

return a 404 for not found api, module and lib routes

---

README.md

In the README.md file on the 0.4.0 branch, the Travis-CI and David-DM badges were displaying the status of the Master Branch, not the 04.0 branch.

Switch TravisCI and DavidDM to 0.4.0 branch

---

modules/users/tests/server/user.server.model.tests.js

Adding couple more tests to confirm users model works as expected.
Also confirms PR https://github.com/meanjs/mean/pull/439 is working as expected.

Enhancing users model tests

---

config/config.js

When running grunt prod with `secured` mode enabled for SSL support, and there were missing key/cert files then the server would fall back to HTTP-only and would notify of the missing SSL files.
Enhancing error message with an actual instruction on how to fix the missing ssl problem when running in prod mode and secured enabled
Addresses concern reported in #678

Enhancing SSL error message

---

config/assets/default.js
gruntfile.js
gulpfile.js

If you are running gulp, and edit the gruntconfig.js file, gulp will restart.  This change is to separate automation configuration changes so that gruntfile.js updates do not restart the gulp process.
Additionally, this adds gulpconfig.js monitoring so that it will restart gulp if there are changes to gulpconfig.js
There is an issue on windows with path separator when compiling less/sass with gulp.  Grunt does not have this issue.

Task Enhancements

---

modules/users/server/config/strategies/github.js

If a user's displayName in github is undefined, default to the username.
Fixes #519

If displayName in Github is undefined

---

.gitignore

Adding files to ignore that are related to Visual Studio, and Node.js
development within the VS environment.
This is my first PR for a forked repo. I figured it's a good starting point, to get used to the flow of PR's, and contributing to this project. Also, it will help keep my fork clean from VS files moving forward. 
@lirantal @ilanbiala Please let me know if this is an appropriate PR, and that I'm following the proper flow for this project. Thanks.

Added Visual Studio files to gitignore

---

modules/articles/client/config/articles.client.routes.js
modules/chat/client/config/chat.client.routes.js
modules/core/client/app/init.js
modules/users/client/config/users.client.routes.js
modules/users/client/controllers/settings/settings.client.controller.js

New PR for requiring client side roles.  Props to @igorauad for the idea.

Require login

---

.gitignore
modules/core/server/views/layout.server.view.html

- Moving a few meta tags+base tag before the title. I've noticed Bootstrap [recommends this](http://getbootstrap.com/getting-started/#template) (wasn't sure why) so I did some quick googling and [IE seems to be the reason](http://blogs.msdn.com/b/ieinternals/archive/2011/07/18/optimal-html-head-ordering-to-avoid-parser-restarts-redownloads-and-improve-performance.aspx) but there were some other speculations, too. Feel free to search more.
- ...in any case, [charset tag should come before the title](http://www.w3.org/wiki/The_HTML_head_element#Stop_right_there.21_Inline_CSS_and_JavaScript_is_not_too_clever.21).
- Removing keyword tag since it [isn't really used anymore](https://chrisedwards.me/seo/keyword-meta-tag-google/).
- Removing duplicate Content-type/Encoding tag
- Adding …

Putting the head in order

---

modules/articles/client/config/articles.client.routes.js
modules/chat/client/config/chat.client.routes.js
modules/core/client/config/core-admin.client.menus.js
modules/core/client/config/core-admin.client.routes.js
modules/core/client/core.client.module.js
modules/users/client/config/users-admin.client.menus.js
modules/users/client/config/users-admin.client.routes.js
modules/users/client/config/users.client.routes.js
modules/users/client/controllers/admin/user-list.client.controller.js
modules/users/client/controllers/admin/user.client.controller.js
modules/users/client/services/users.client.service.js
modules/users/client/users.client.module.js
modules/users/client/views/admin/user-edit.client.view.html
modules/users/client/views/admin/user-list.client.view.html
modules/users/client/views/admin/user.client.view.html
modules/users/server/controllers/admin.server.controller.js
modules/users/server/policies/admin.server.policies.js
modules/users/server/routes/admin.server.routes.js

Supersedes https://github.com/meanjs/mean/pull/615

Admin module

---

config/env/development.js
config/env/production.js
config/env/test.js
config/lib/mongoose.js

Enhancing support for development environment to enable mongoose debug mode so that we can debug db queries
PR submitted out of original idea from https://github.com/meanjs/mean/pull/143

Enabling mongoose debug mode

---

_config.yml

Exclude the node_modules directory just in case it's left behind from another branch.

Excluded node_modules

---

karma.conf.js
modules/articles/tests/client/articles.client.controller.tests.js
package.json

* Adding karma-ng-html2js-preprocessor to preprocess angular templates into js.  
* Adding user mock to articles tests.
Fixes #711 using [karma-ng-html2js preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor).

Fixing karma tests

---

bower.json

Setting angular-file-upload version in Bower.json to be static at 1.1.5
Fixes meanjs/mean#722 & PR meanjs/mean#724

Updated angular-file-upload to use static dependency

---

modules/articles/server/controllers/articles.server.controller.js
modules/articles/tests/server/article.server.routes.tests.js

The article middleware was calling getErrorMessage with a null argument, causing a crash when this method tried to access 'code' on an null parameter.
The bug was not exposed by the original test, since it was mixing two (related) aspects:
* An invalid Id (a badly formed mongodb identifier)
* An non-existent Id (an identifier with no corresponding document in the database)
Modifications:
- Fixed the message property in the article controller (the error message follows the wording of the error message in "users.password.server.controller.js", in case of username not found)
- Added a new test to check modifications and avoid regressions

Article middleware was calling getErrorMessage with a null argument

---

public/application.js

Correct the issue of Google OAuth2 redirect missing the hashbang after enabling GooglePlus API - Fixes #535
Thanks to the discussion on #535 and the fix from @junit38

Fix the Google OAuth Redirect Bug - #535

---

modules/core/client/app/init.js
modules/users/client/controllers/authentication.client.controller.js
modules/users/client/views/authentication/authentication.client.view.html
modules/users/server/controllers/users/users.authentication.server.controller.js
modules/users/server/routes/auth.server.routes.js

In response to #185
Two different strategies are adopted, one for when the user authenticates locally and the other through providers. When authenticating locally, the signin function in the client controller redirects to the previous state (storing and using a state name) after successful login. When authenticating through a provider, the first call to provider stores the previous URL (not state, URL) in the session. Then, when provider actually calls the authentication callback, session `redirect_to` path is used for redirecting user.
Note: I originally did this to master, so there is one extra thing to correct. First, note on branch master sign-in and signup are not nested states. Given they are nested in 0.4.0, the controller instantiated in the nested state does not capture the …

Enable redirection to previous page after login

---

gruntfile.js

Using Grunt's internal [mkdir()](http://gruntjs.com/api/grunt.file#grunt.file.mkdir).
It creates the folder only if it doesn't exist already.
Alternative solution for #584

Add Grunt task to make sure uploads directory exists

---

generator.html

@lirantal @ilanbiala 
This is what I was thinking about doing for the notice about the generator. So it's still on the website, and still listed in the 0.3.x version of the docs, it's just removed from the 0.4.0 docs and and 0.4.0 README until we get it ready to use for 0.4.x.

Add generator notice

---

README.md
modules/core/client/views/home.client.view.html

Removed generator references from the README and index view. 
@ilanbiala @lirantal - I would suggest this get merged into 0.4.0 prior to the release to prevent confusion.

Remove generator references from readme and index

---

.gitignore

updating gh-pages gitignore to ignore the public/ and config/ directories which exist on master and other dev branches, this is so we can work seamlessly on different branches (gh-pages vs dev branches)

Updating .gitignore 

---

.gitignore

updating gitignore file to disregard the _site/ directory which gets created when using jekyll for generating the gh-pages documentation branch locally

Gitignore for Jekyll assets

---

modules/users/tests/server/user.server.model.tests.js

re-factoring the server model tests to create user model from schema only during tests, so that we can re-use mongodb's _v versioning fields, and also cleaning up user tests on each test iteration

Refactoring Tests for User model

---

scripts/reset-password.js

Resolved issues:
* models are not loaded.  Regression from #736 (https://github.com/meanjs/mean/pull/736/files#diff-d8679454c2d07935926663de0e9cc9a1L34)
* callback was not passed corresponding user data.
* process exits before mail queue is processed.
Enhancements:
* suppress error messages unless debug mailer option is true.
* from e-mail address comes from config.
* added marker messages to each callback line. (Example: [processed/total] Could not send email for x)
* added status message on-complete to tell how many successful e-mails were sent.

Bug: reset-password enhancements and bug fix

---

.travis.yml
gruntfile.js

Updating grunt 'force' option to default/force it to false so that we can fail any task that is failing and thus fail the build in case of any issues in tests, jshint conventions, and so on.
This ensures that our CI process is catching any issues.

Grunt - fail the build if a task fails

---

modules/users/tests/server/user.server.model.tests.js

refactoring the async nature in the user model tests to account for mocha 2 second timeouts causing travis-ci build fails

Updating User model tests for synchronous test and fixing done() calls

---

README.md
_includes/docs/0.3.x/angularjsmodules.html
_includes/docs/0.3.x/configuration.html
_includes/docs/0.3.x/folderstructure.html
changelog.html
generator.html

* Fixing typos in README.md
* Fixing typos in legacy 0.3.3 documentation

fixing typos across documentation in gh-pages

---

README.md

Since we agreed to make the master branch the current live branch, and the stable releases will be tagged under releases, I removed the development badges from the README.

Remove Dev Branch Badges

---

.jshintrc

removing deprecated options in the latest versiosn of jshint which will be replaced by adding JSCS settings.
@rhutchison when you add your JSCS PR this PR will complement it to remove those code style options from JSHINT which are deprecated

Updating JSHINT settings

---

modules/articles/client/config/articles.client.routes.js

Currently, the API on the server allows anybody (regardless if signed in or not) to retrieve a list of articles. However, the client requires the user to be logged in to view the articles. This makes it so visitors that are not authenticated to view the articles. 
This goes along with #780 that makes the TopBar visible by default.

Allow Guests to view Articles

---

modules/users/tests/server/user.server.model.tests.js

fixing up a user model test which was not setup correctly without the async done() callback, which led to false postivies. Adding timeouts to the test ensures that the test completes in time, otherwise mocha's 2s timeout will fail the test

Fixing user model test's last test which fail or report a false positive

---

config/env/default.js
config/lib/express.js

Adding support for sessionKey configuration parameter to allow to easily change the session key that is used to hold the session value. The default is a generic sessionId key to introduce security through obscurity.

Express sessionKey configuration option

---

modules/users/tests/server/user.server.model.tests.js

This further strengthens our test suites from 21 tests to 35 already!

Adding suite of tests for the e-mail validation field in the users model

---

config/config.js
config/lib/express.js
karma.conf.js
modules/articles/client/config/articles.client.routes.js
modules/chat/client/config/chat.client.routes.js
modules/core/client/config/core.client.routes.js
modules/core/client/views/home.client.view.html
modules/core/server/views/layout.server.view.html
modules/users/client/config/users-admin.client.routes.js
modules/users/client/config/users.client.routes.js
modules/users/client/views/authentication/authentication.client.view.html
modules/users/client/views/settings/manage-social-accounts.client.view.html
modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/server/models/user.server.model.js

Not ready to merge yet.  Need to collaborate on someone more familiar with the inner Node workings.  @lirantal @ilanbiala @rhutchison

Initial commit to return /client to the URL include paths

---

modules/articles/client/config/articles.client.config.js
modules/chat/client/config/chat.client.config.js
modules/core/client/services/menus.client.service.js
modules/core/tests/client/menus.client.service.tests.js

Make TopBar Public By Default

---

config/lib/socket.io.js

New enhancements to the Express session, added "sessionId" as the new
default session key. Previously, the express session was using the
default "connect.sid" key. This caused the Socket configuration to be
unable to find the session id, thus causing issues with the Socket. One
such issue, was that the same Socket would be used for all users
connected to the server.
This also adds a bit more error handling of the Socket server
configuration.

Fixed bug with Socket IO session

---

modules/core/client/services/menus.client.service.js
modules/core/tests/client/menus.client.service.tests.js

Fixing Menus service removeMenuItem and removeSubMenuItem by..
* modified tests to reproduce issues
* replaced references to old link property with new state property
Fixes #777 and replaces #778.

Fixing Menus service remove bugs.

---

config/env/default.js

Set default session cookie maxAge from 24 minutes to 24 hours.
Sorry @lirantal only noticed now :P

fix default session cookie maxAge

---

gulpfile.js

The current gulpfile 'prod' task runs the 'build' subtask which sets the environment variable to development.  This pull request correctly sets the environment variable to production following completion of the build subtask.

Corrected 'prod' task in gulpfile

---

modules/users/tests/server/user.server.model.tests.js

@lirantal Great job on the email tests you added. I took that and added it against my group's project and they all passed, but when I added the following it failed. It currently passes in the MEAN.js project, but I think it's worth checking for in case we switch validators down the road.

[test] Allow an email with sub domains

---

.bluemix/pipeline.yml
README.md

After adding support to deploy MEANJS to Cloud Foundry, this pull request adds support for the "Deploy To Bluemix" button.  With a single click this button will deploy a working copy of MEANJS to Bluemix.  In addition to the running instance of MEANJS in the cloud, it also creates a copy of the code in a Git repo in Bluemix and sets up a build and deploy pipeline to the repo.  This allows the user to deploy changes made to MEANJS to Bluemix just by doing a `git commit`.
To see this functionality in action you can checkout the [README in my fork](https://github.com/ryanjbaxter/mean).  Just click the Deploy To Bluemix button to test it out.

Added Deploy To Bluemix button to the README

---

modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js

Fixes #829.
If the password was exactly 6 characters long, the password would not get hashed and was being stored in the database as plain text. I added a couple tests to ensure the password wasn't being stored in plain text as well as fixed the logic that was skipping over the password hashing. 
Thanks @sparshy! :-D

[fix] Was storing a 6 char password in plain text [fixes #829]

---

modules/core/client/app/init.js
modules/core/client/config/core.client.routes.js
modules/users/client/controllers/authentication.client.controller.js

This addresses the issue with redirecting to a not-found/exception state after login.
1. http://localhost:3000/khdshskddsakh
2. Click Sign In & Authenticate
User should be redirected to the previous valid state or default state (home).
User is redirected to 'not-found' state.

[Bug] Previous State (History)

---

modules/core/client/config/core.client.routes.js

This will mask the not-found route by showing the not-found page without redirecting to the not-found state.
1. http://localhost:3000/khdshskddsakh
* Route should not change.
* User should see page not found.

mask exception route for 404 responses.

---

modules/core/client/app/init.js
modules/core/client/config/core.client.routes.js
modules/core/client/services/interceptors/auth.interceptor.client.service.js
modules/core/client/views/400.client.view.html
modules/core/client/views/403.client.view.html
modules/core/tests/client/interceptors/auth.interceptor.client.tests.js

Reintroducing to master branch.  closing https://github.com/meanjs/mean/pull/727
@ilanbiala @lirantal @rhutchison @codydaig

Unauthorized client side routing

---

.jshintrc
modules/core/client/app/init.js
modules/users/server/config/strategies/facebook.js

Closes #202, and closes #697 - if user does not authorize email scope, email will not be mapped.  Username will be generated from first initial of first name and last name.
.jshint latedef set to nofunc.

Facebook authentication

---

bower.json
config/assets/default.js
config/assets/production.js
modules/articles/client/controllers/articles.client.controller.js
modules/articles/client/views/create-article.client.view.html
modules/articles/client/views/edit-article.client.view.html
modules/articles/tests/client/articles.client.controller.tests.js
modules/core/client/app/config.js
modules/core/client/css/core.css
modules/core/client/directives/show-errors.client.directives.js
modules/users/client/controllers/admin/user.client.controller.js
modules/users/client/controllers/authentication.client.controller.js
modules/users/client/controllers/settings/change-password.client.controller.js
modules/users/client/controllers/settings/edit-profile.client.controller.js
modules/users/client/views/admin/user-edit.client.view.html
modules/users/client/views/authentication/signin.client.view.html
modules/users/client/views/authentication/signup.client.view.html
modules/users/client/views/settings/change-password.client.view.html
modules/users/client/views/settings/edit-profile.client.view.html
modules/users/tests/client/authentication.client.controller.tests.js

Add validation on the client to validate form data prior to posting to the server.

client-side form validation with ng-messages.

---

modules/articles/client/views/create-article.client.view.html
modules/articles/client/views/edit-article.client.view.html
modules/articles/client/views/list-articles.client.view.html
modules/articles/client/views/view-article.client.view.html
modules/chat/client/views/chat.client.view.html
modules/core/client/css/core.css
modules/core/client/views/header.client.view.html
modules/core/client/views/home.client.view.html
modules/core/server/views/index.server.view.html
modules/core/server/views/layout.server.view.html
modules/users/client/views/admin/user-edit.client.view.html
modules/users/client/views/admin/user-list.client.view.html
modules/users/client/views/admin/user.client.view.html
modules/users/client/views/authentication/authentication.client.view.html
modules/users/client/views/authentication/signin.client.view.html
modules/users/client/views/authentication/signup.client.view.html
modules/users/client/views/password/forgot-password.client.view.html
modules/users/client/views/password/reset-password-invalid.client.view.html
modules/users/client/views/password/reset-password-success.client.view.html
modules/users/client/views/password/reset-password.client.view.html
modules/users/client/views/settings/change-password.client.view.html
modules/users/client/views/settings/change-profile-picture.client.view.html
modules/users/client/views/settings/edit-profile.client.view.html
modules/users/client/views/settings/manage-social-accounts.client.view.html
modules/users/client/views/settings/settings.client.view.html

Remove the 'data' prefix from custom attributes.

Remove 'data' prefix from attributes

---

modules/users/tests/server/user.server.model.tests.js

1. Refactoring variables usage through-out the tests
2. Fixing correct error handler tests were previously these would report a false positive isue
3. Fixing recent unit tests to be added as part of the main save method suite
4. Fixing an issue with the tests which didn't clean the user1 entry in the db and so tests following it would fail regardless of the validation
5. Fixing one test to actually be valid use case

Major Fixing and Refactoring tests

---

modules/users/client/views/admin/edit-user.client.view.html
modules/users/client/views/admin/list-users.client.view.html
modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js

These changes make the role field required in the User model. Changes to
the Admin user edit view were added to provide validation for the role
field.
As an added enhancement, the user's roles are displayed in the Admin
user list view.
Added model tests to accommodate these changes.

Admin users require role

---

modules/users/tests/server/user.server.model.tests.js

@lirantal PR #840 changed the global var `user` to `user1` in the User model server tests. This was merged and then #858 was merged, which was still referencing the global var as `user` in the new *roles* tests. This is causing jshint failures.
This change updates the new *roles* tests to use `user1`

[hotfix] Fixed User model tests

---

README.md
gruntfile.js
modules/articles/tests/server/article.server.model.tests.js
package.json
test.js

Code coverage is now built-in to our project and grunt tasks!
and further results:
To run the code coverage simply execute:
```bash
grunt coverage
```
Addresses:
* https://github.com/meanjs/mean/pull/569
* https://github.com/meanjs/mean/pull/760

Adding coverage report for server-side tests using istanbul

---

config/assets/cloud-foundry.js

Since the CF env assets doesn't contain anything specific, I stripped it down so it will default to the default settings. 
Closes #861 
@ryanjbaxter

[bug] Remove non CF specific files [closes #861]

---

modules/users/client/directives/users.client.directive.js
modules/users/client/views/authentication/signin.client.view.html
modules/users/client/views/authentication/signup.client.view.html
modules/users/client/views/password/forgot-password.client.view.html
modules/users/client/views/password/reset-password.client.view.html
modules/users/client/views/settings/edit-profile.client.view.html
modules/users/server/config/strategies/local.js
modules/users/server/controllers/users/users.password.server.controller.js
modules/users/server/models/user.server.model.js

* add directive to force username & email to lowercase
* remove sensitive data in password reset
* 2 spaces indentation  in reset & forgot password views

Reopened: Force Username & Email to Lowercase + Remove Sensitive Data

---

_includes/docs/0.4.x/cloud-foundry.html

We have already added the Deploy to Bluemix button to the REAME, I am just adding the same button to the CF section of the documentation as well.
@codydaig

Add Deploy to Bluemix button to documentation

---

.travis.yml

This addresses the code coverage running as part of our CI in https://github.com/meanjs/mean/pull/811

Adding another job for Travis CI to run the `grunt coverage` task on every build

---

config/config.js
config/lib/app.js
package.json

I've been thinking it would be great if we can display the project version number when the app starts as that will easily allow other devs and users to clearly see which MEAN.JS release they are on.
We often get a lot of bug requests and this is usually the first version that comes up...
WDYT?

Adding MEAN.JS version information as part of the startup info when app loads

---

modules/articles/server/config/articles.server.config.js

Dummy config directory for the articles module to make it easier for developers to understand and realize there's an actual per-module config/ directory/files that can be added
This came up from my gitter conversation with @trainerbill who was asking about modularizing the configuration approach so that modules can have their own config tasks and didn't realize it already existed and requested to have a 'sample' directory/file for the articles module as a general guide.

Adding sample config/ directory for articles module

---

README.md

In reference to #793.
Not entirely sure how much I like the wording, so any suggestions would be awesome!
@trainerbill

Add seed user instructions to README

---

.travis.yml

Adding support for nodejs v4 and allowing it to fail without failing the complete build for CI.
Closes #902.

Supporting NodeJS v4 in Travis CI

---

bower.json

- Remove deprecated "version": http://bower.io/docs/creating-packages/#version
- Add "license"
- Add "homepage"
- Use fuzzier version requirement for angular-messages (~)

Update Bower manifest

---

config/lib/seed.js
modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js
package.json

Fixes the database seeding bug with the password not passing the owasp
test. Related to #908 & #909 
Adds a UserSchema method that generates a random password that passes
the owasp test.
Performed minor refactoring of the database seed configuration to
implement the new UserSchema method.

[hotfix] Fixes db seed password bug

---

gulpfile.js

This PR fixes #873. The models were never getting loaded in the gulp tests so it was freezing on mongoose errors. This loads the models before running the server tests.

[bug] Gulp test wasn't running server tests [closes #873]

---

modules/core/client/app/init.js
modules/users/tests/client/authentication.client.controller.tests.js

`$stateChangeSuccess` event should be signaled in order to allow "recording" of previous state. 
This part of the implementation was missing, I just realized that.

Fix redirection to previous state after required authentication

---

modules/users/client/directives/password-validator.client.directive.js
modules/users/client/directives/password-verify.client.directive.js
modules/users/client/services/password-validator.client.service.js
modules/users/tests/server/user.server.model.tests.js

fixing jshint issues by requiring single quotes

fixing jshint single quotes issues

---

config/lib/app.js
config/lib/mongoose.js
config/lib/seed.js
modules/core/tests/server/core.server.config.tests.js
modules/users/tests/server/user.server.model.tests.js

Refactoring the seeddb logic to work with promises all over due to all the async behavior.
This lays the ground for further work on adding tests for SeedDB functionality.

SeedDB Refactoring

---

modules/articles/tests/server/article.server.model.tests.js
modules/articles/tests/server/article.server.routes.tests.js
modules/chat/tests/server/chat.socket.tests.js
modules/core/tests/server/core.server.config.tests.js
modules/users/tests/server/user.server.model.tests.js
modules/users/tests/server/user.server.routes.tests.js

Added a timeout of 10000 ms to each server test file. This is an attempt
to solve the timeout issues that we're experiencing with the Mocha
tests. Especially, this is hoping to address the build fails that are
caused by such timeouts.
Issue is described in https://github.com/meanjs/mean/issues/955

Mocha test timeouts [fixes #955]

---

gruntfile.js
gulpfile.js
modules/articles/tests/e2e/articles.e2e.tests.js
modules/users/tests/e2e/users.e2e.tests.js
package.json

fixing grunt and gulp e2e tests

---

.travis.yml
modules/users/tests/server/user.server.routes.tests.js
package.json

Adding the required support to properly build the nodejs v4 edition.
Source and credit originated from: https://github.com/lirantal/meanjs/pull/1

NodeJS v4 support - fixing the failed build

---

config/config.js
config/env/default.js
config/env/local.example.js
modules/core/tests/server/core.server.config.tests.js

adding ability to configure session.secret in local env config

---

.travis.yml
protractor.conf.js

Adding protractor options to fix travis failing

---

modules/users/server/models/user.server.model.js

This solves the issue of the User model's `pre('validate')` method, attempting to validate against a password that was not modified.
Adds the `this.isModified('password')` check to the condition.

[bug] Solves User model validation issue with tests [fixes #966]

---

gruntfile.js
gulpfile.js
modules/articles/tests/server/article.server.model.tests.js
modules/articles/tests/server/article.server.routes.tests.js
modules/chat/tests/server/chat.socket.tests.js
modules/core/tests/server/core.server.config.tests.js
modules/users/tests/server/user.server.model.tests.js
modules/users/tests/server/user.server.routes.tests.js

Added the timeout option to the Mocha grunt task; set to 10000.
Removed the individual test suite timeouts, for all server tests.
As discussed in #964

Global Mocha timeout

---

config/env/development.js
config/env/production.js
config/env/test.js
config/lib/app.js
config/lib/seed.js
modules/core/tests/server/core.server.config.tests.js

Added an options object to the database seed configuration. Currently, the only option implemented is `logResults`; set to 'true' by default.
Setting the logResults option to `false` in the core configuration server test suite.
The initial reason for this option is to disable the console output of the seed db events, while running the test coverage. However, this can be useful in other cases. For instance, if the user doesn't want the passwords displayed in the console where they may be comprimised.

Seed options - logResults

---

_includes/docs/0.4.x/gettingstarted.html
generator.html

Fixed Generator Repo link on getting started page and 0.4.1 documentation page

Fix 404 error on Generator Repo link

---

_includes/docs/0.4.x/gettingstarted.html

Closes https://github.com/meanjs/mean/issues/953

fixed #953 - updated the correct URL in documentation and website to obtain the 0.4 version

---

config/lib/seed.js
modules/core/client/directives/show-errors.client.directives.js
modules/core/tests/client/interceptors/auth.interceptor.client.tests.js
modules/core/tests/client/menus.client.service.tests.js
modules/core/tests/server/core.server.config.tests.js
modules/users/client/directives/password-validator.client.directive.js
modules/users/client/directives/password-verify.client.directive.js
modules/users/server/config/strategies/facebook.js
modules/users/server/config/strategies/github.js
modules/users/server/config/strategies/google.js
modules/users/server/config/strategies/linkedin.js
modules/users/server/config/strategies/local.js
modules/users/server/config/strategies/paypal.js
modules/users/server/config/strategies/twitter.js
modules/users/tests/server/user.server.routes.tests.js

This has all the formatting changes and ESLint support (temporarily so we can confirm it passes in Travis).

Formatting fixes for ESLint

---

gruntfile.js
gulpfile.js
modules/users/client/directives/password-validator.client.directive.js
modules/users/client/directives/password-verify.client.directive.js
modules/users/client/views/authentication/signup.client.view.html
modules/users/client/views/password/reset-password.client.view.html
modules/users/client/views/settings/change-password.client.view.html
modules/users/tests/client/password-validator.client.directive.tests.js
modules/users/tests/client/password-verify.client.directive.tests.js
modules/users/tests/client/password.client.controller.tests.js
modules/users/tests/e2e/users.e2e.tests.js

Renaming strength meter to requirements meter, hiding when password field is empty, and refactoring directives to use $validators, adding tests

Hiding the Password Strength progress when the field is empty

---

gruntfile.js

fixing #961, failing grunt task will fail the travis build which is the desired behavior

Adding configuration to fail grunt task if e2e tests fail

---

config/env/test.js
gruntfile.js
karma.conf.js
package.json

Adding karma coverage for displaying client side test coverage when running `grunt coverage`.

Adding karma coverage to grunt

---

modules/core/server/views/layout.server.view.html

Removed `{{url}}` from the Favicon path. This fixes the intermittent issues with the path resolving to an invalid location.
This seems to fix the bug with the Favicon invalid path. However, as discussed in #979, there are still remaining questions as to why these lines are using `locals.url` and `locals.logo` with the META tags
https://github.com/meanjs/mean/blob/master/modules/core/server/views/layout.server.view.html#L17-L29
Does anyone have any insight into these, and how we should address these issues? I think it would be appropriate to address all these issues in this PR. We just need to decide on how.

[bug] Favicon invalid path [fixes #979]

---

.travis.yml

Closes #898   - addressing the issue where the webhook API is hard-coded into the travis config file

Moving Travis CI webhooks config to environment variable 

---

package.json

MAJOR BUG!!
(the app does not run until this is merged in)
The latest release of mongoose this morning broke changes in the repo. #1008 proves this by removing the cache in travis and forcing travis to use the latest version of mongoose.

[hotfix] Lock mongoose version to a working version

---

config/env/development.js
config/env/production.js
config/env/test.js
config/lib/express.js
config/lib/logger.js
modules/core/tests/server/core.server.config.tests.js
package.json

Adds the log options, and format to the Morgan middleware in the Express configuration.
These options are defined in the environment configurations.
The implementation derived from https://github.com/meanjs/mean/pull/254 by @lirantal, which somehow got overlooked when merging 0.4.0 into master.
Related to the discussion in #975, and taking over for @codydaig #982

[bug] Enable log options for Morgan that were missed in the 0.4.0 merge

---

config/env/default.js
config/lib/express.js
config/lib/multer.js
modules/users/client/controllers/settings/change-profile-picture.client.controller.js
modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/tests/server/user.server.routes.tests.js
package.json

updating profile upload with a new version of multer

---

config/env/development.js

Reverts the default Logger setting to use the stdout by default, rather than the stream option for the Development env config.
I realized this might trip some users up, since when the Logger config was implemented (https://github.com/meanjs/mean/commit/8cd2291a6a8d14cc7a75320944c532ff8b41668f)  I had overlooked the fact that users probably wouldn't want the Stream option turned on by default.

[hotfix] Logger Development config default

---

package.json

@ilanbiala I'm going to recommend if this passes Travis that this gets held off until 0.5.0 since it also bumps a minor version.

Update Mongoose Version

---

config/env/cloud-foundry.js
config/lib/app.js

Adds a check for the existence of the seedDB config setting, before
attempting to read config.seedDB.seed setting.
Solves the problem when the seedDB config setting is missing from a
environment config, that causes the application to throw an exception at
startup.
As pointed out by @ryanjbaxter, due to the `seedDB` setting missing from the Cloud-Foundry env config.

[hotfix] SeedDB missing in env config

---

modules/users/tests/server/user.server.routes.tests.js

Removes a duplicate User CRUD test for Profile Picture.
There are two reasons for this commit.
1) Duplicate of https://github.com/meanjs/mean/blob/master/modules/users/tests/server/user.server.routes.tests.js#L833-L848
2) This test is problematic in Windows environment.
Related to:
https://github.com/visionmedia/supertest/issues/230
https://github.com/visionmedia/supertest/issues/258
The latter may be an issue with the `.attach` method not completely loading the file into memory before the 400 status response is sent back due to no User logged in.

Duplicate CRUD Test - Profile Picture

---

.travis.yml

Having cache on the build is gibing us a false positive. As soon as I remove the cache, it will use the latest npm modules, and let us know when it's truly failing because of package dependencies.
I cloned the repo into a new directory and I'm getting the same mongo error locally as this PR is able to duplicate on the server.

[bug] Dont use Cache

---

README.md

Issue #743 - Adding Gulp.  
The basics have been added, but I will continue to add onto this throughout the week for another commit in the short future.

Added short Gulp Section to Intro

---

README.md

The link to the live demo in the README is broken. 
Credit @marqshort for discovering it.

bug(readme): Remove Broken Live Demo Link

---

.travis.yml
README.md

Added Node 5 to the `.travis.yml`, but allowed failures. Since Node v5 uses npm 3 there's some work to be done to support it. 
Since the build is currently failing on Node 5, I added a note to the README under the prerequisites to make clear that Node 5 is not supported at this time.

test(travis): Add Testing for Node 5

---

README.md
config/env/cloud-foundry.js
manifest.yml

Fixes #1029 
The MongoLabs service in Bluemix is being removed so we need to use a different Mongo service.

Switched to using new MongoDB service in Bluemix

---

_includes/docs/0.4.x/cloud-foundry.html

The MongoLabs service in Bluemix is being removed so we need to update the documentation to use a different MongoDB service.

Updated MEANJS 4.x documentation for Bluemix

---

_includes/docs/0.4.x/gettingstarted.html
_includes/docs/0.4.x/troubleshooting.html

Gulp Setup and Troubleshooting sections added to the 0.4.x docs.

#1006 Added Gulp Setup and Troubleshooting to docs/0.4.x

---

_includes/docs/0.4.x/index.html

Small typo on the 0.4.x documentation in the documentation alert div here: http://meanjs.org/docs/0.4.x/
Change "...please let us know by submitting on issue on github ..." to "...please let us know by submitting an issue on github ...". Changing first "on" to "an".

Fix typo on Docs 0.4.1

---

.travis.yml
gulpfile.js
package.json

Fix npm warnings

---

.gitignore
config/config.js
config/env/local.example.js
gruntfile.js

**EDIT: 10/29/2015**
**This PR has changed quite a bit, and originally was not properly described. Please see the below commit, and discussion.**
Enables the setting of the test database configuration inside of the local environment config. If this setting is present, then it will override the db setting in the Test environment config. This will compliment the already existing `db` setting in local.js.
I've also added environment variables to Production, Test, and Development:
`process.env.MONGO_USER`
`process.env.MONGO_PASS`
This is both an enhancement, and support feature. Newer versions of MongoDB are deprecating MONGODB-CR authentication. Going forward it is best practice to provide the `user` & `pass` options with the mongoose `connect` method.
This also enhances the experience of a …

feat(config): Local environment configurations

---

.bluemix/pipeline.yml

I tried to use the bluemix deploy button. There was an error with running rvm in the deployment phase.
After changing the path everything worked smoothly.

change rvm path for bluemix deployment

---

modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js

supporting valid email (i.e. root@admin) according to HTML5 and RFC 822
fixing #934

supporting valid email (i.e. root@admin)

---

gulpfile.js
package.json

Adds a Gulp task that watches all server files (including server tests),
and upon any changes it will perform the Gulp *test:server* task.
Also, includes an **optional** argument for the task that can specify
that if the changed file is a test, then it will only run that test
file.
Example usage: gulp test:server:watch --onlyChanged

feat(config): Gulp Server Watch for Mocha

---

modules/articles/client/views/list-articles.client.view.html
modules/articles/client/views/view-article.client.view.html
modules/articles/server/policies/articles.server.policy.js
modules/articles/tests/server/article.server.routes.tests.js

Adds an additional check for the existence of a populated user reference, when determining if the current user has immediate access to the requested article.
Without this fix, the server will throw an error if the requested article doesn't have a populated user field.
Modified the article & articles list view's to check if the article has a populated user. If not, then it will display "Deleted User" in place of the missing user reference.
Fixes #1082

fix(articles): Orphaned User reference throws server error

---

config/env/default.js
config/env/production.js
config/lib/app.js

Adding the functionality of configuring the host to start the server. 
By default set this to `127.0.0.1` as the best practice is to run the server locally and expose the port via a proxy like nginx.

Adding host configuration feature

---

modules/core/tests/server/core.server.config.tests.js

logger test failed on undefined variable

fix(tests) fixing assertion test for logger which failed

---

modules/chat/client/chat.client.module.js
modules/chat/client/config/chat.client.config.js
modules/chat/client/config/chat.client.routes.js
modules/chat/client/controllers/chat.client.controller.js
modules/chat/client/views/chat.client.view.html
modules/chat/tests/client/chat.client.controller.tests.js

I know this will further stir the pot about which guidelines the project should follow, but the intention is not to delay progress, and instead push forward.
This is not up for debate - but I will take constructive feedback.

feat(chat): Modify chat module to implement johnpapa styleguide.

---

modules/core/client/app/init.js

Adds a check for the existence of the "guest" role in the client route
state configuration of `data.roles` in the $stateChangeStart of core
client app init configuration.
If this role is present then it doesn't attempt to check authentication
on the route that is being transitioned to.
Fixes https://github.com/meanjs/mean/issues/1098

fix(core): Client routes guest access bug

---

modules/core/server/controllers/core.server.controller.js

To handle potential security issues with XSS - the following PR introduces:
* refactoring the user object that gets populated in the server-side to achieve: 1. a pre-defined sub-set of the user object will be passed to the client side for usage; 2. escaping possible malicious XSS strings such as username, displayName, etc.
Fixes #1106

fix(security): fixing possible xss issue in parsed objects

---

CONTRIBUTING.md

Fixes 'consice' typo to 'concise' in CONTRIBUTING.md
Was originally in #1135, now moved to separate PR.
Fixes #1136

fix(documentation): Contributing.md typo

---

config/assets/default.js

Changed config properties to arrays for inclusion in Gruntfile Lodash unions, e.g. linting. Also fixes typo in CONTRIBUTING.md
Fixes #1125

fix(config): Added Gruntfile linting

---

gulpfile.js

Fixes an error occurring when running `gulp`:
```bash
/mean/gulpfile.js
199:22  error  A space is required after '{'   object-curly-spacing
199:42  error  A space is required before '}'  object-curly-spacing
```

fix(build): Linting error at gulpfile.js

---

modules/core/server/controllers/core.server.controller.js

~~Adds angular-sanitize to the project, and uses it to sanitize the
profileImageURL field of the Authentication.user object.~~
Based on the conversation in #1127, I've decided to revert the original changes in this PR & merely remove the `validator.escape` call on the `profileImageUrl` field. We don't need to worry about vulnerabilities on this field.
Fixes https://github.com/meanjs/mean/issues/1127

fix(users): ProfileImageURL sanitize with ngSanitize

---

package.json

changed PhantomJS and SocketIO dependencies to ~ to stop breaking changes.

fix(Travis build): PhantomJS and SocketIO dependencies

---

bower.json
modules/core/client/views/header.client.view.html
modules/users/client/views/admin/list-users.client.view.html
modules/users/client/views/authentication/signin.client.view.html
modules/users/client/views/authentication/signup.client.view.html
modules/users/client/views/password/reset-password.client.view.html
modules/users/client/views/settings/change-password.client.view.html
modules/users/tests/client/password-verify.client.directive.tests.js

Moving from 0.13 solves many the many issues with this version, provides a more stable interface.
Migration guide: https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes
Closes #1142 
Closes #1131

feat(config): upgrade angular-bootstrap from 0.13 to 1.0

---

modules/core/server/controllers/core.server.controller.js

Needed for management of social accounts.

fix(core): Add "additionalProvidersData" to "safeUserObject"

---

modules/articles/client/views/view-article.client.view.html
modules/articles/server/controllers/articles.server.controller.js
modules/articles/tests/server/article.server.routes.tests.js

Adds validation of the owner of an Article to fix a bug with the current
validation logic, in the edit Article view.
Since we're not storing the User's `_id` field in the client-side User
object any longer, the validation of whether or not the current User is
the owner of an Article is broken.
These changes fix the issue, by adding a property to the vm in the
articles client controller; `vm.isOwner`. This property will determine
whether or not the edit & delete buttons are available to the currently
logged in User when viewing an Article.
Added a method to the Users client service, for retrieving the currently
logged in User data; `Users.me` performs a GET request to
*api/users/me*.
Fixes #1146

fix(articles): Article edit/delete validation

---

gulpfile.js

The transformUrl replace function has been removed from templatecache gulp task.
The client view routes include the string "/client" in the url from mean.js 0.4.2 and the browser view request is not matching with the angular template cache url, so all the templates cache is being ignored at startup.
The task has been updated.

fix(gulp): Fixing/updating templatecache gulp task

---

gulpfile.js

Adds a task to copy the example local environment config, and save it as a development environment config.
Releated: #1175

feat(gulp): Add the copy:localConfig task to Gulp

---

config/env/default.js
config/lib/express.js
package.json

Added Lusca middleware for CSRF

[feat] Added Lusca middleware for CSRF [fixes #828]

---

package.json

version 1.3.7 installed with the package.json file is 6 releases behind - 1 feature release, and 5 patches. security advisors have been published for older socket.io version

feat(deps): update socket.io dependency

---

README.md

* double "guide" word in the documentation
* Correcting link for ExpressJS guide

fix(docs): updating links, English issues

---

modules/core/client/css/core.css
modules/users/client/views/settings/manage-social-accounts.client.view.html

Adds the User's provider to the list of connect social accounts, when it is also a social account.
This is the first step in solving the issue described in #1032. This at least fixes the bug, of the User's provider not showing up.
We could either merge this to satisfy the bug, and then proceed with the rest of the implementation discussed in the issue. Or we could add it to this PR. We'd still need to discuss, and come to a conclusion of how to handle the different scenarios that end User's can face.

fix(users): Missing primary social provider

---

modules/articles/client/articles.client.module.js
modules/articles/tests/client/articles.client.routes.tests.js
modules/chat/client/chat.client.module.js
modules/chat/tests/client/chat.client.routes.tests.js
modules/core/client/config/core.client.routes.js
modules/users/tests/client/users-admin.client.routes.tests.js
modules/users/tests/client/users.client.routes.tests.js

Prevents transitioning to a URL with a trailing slash.
If a trailing slash is found in the transitioning URL, then the transition is aborted & the user is redirected to the path without the trailing slash.
Adds missing client-side route configuration tests.
Demonstrates that the various route configurations can handle a trailing slash in the URL, and resolve to the correct client route.
Fixes #1075

fix(core): Remove trailing slash from routes

---

package.json

Fixes an issue with Mongoose `4.4.7` that causes the database connection.db property to be  undefined. This issue is causing our builds to fail.
Sets the Mongoose version to `~4.4.3 <4.4.7` for now until we investigate further. This should solve the issue of our failing builds, when the `dropdb` Grunt/Gulp task is ran with the E2E tests.
For more context:
this line https://github.com/meanjs/mean/blob/master/gruntfile.js#L277 was throwing an exception during our builds, since the `dropdb` task is run with the E2E tests. This seemed to cause the Protractor tasks to time-out. However, there was no indication of this exception being thrown from our `dropdb` task when running with `grunt test` or in the Travis builds. I had to explicitly run `grunt test:e2e` to see this exception that led me …

fix(dependency): Mongoose 4.4.7 bug

---

.bluemix/pipeline.yml
package.json

fix(bluemix): Changes Node Version In Bluemix Pipeline
Fixes the requirement that MEANJS requires Node.js 0.12 in order to build.
Fixes #1138

Changes Node Version In Bluemix Pipeline

---

modules/core/server/controllers/errors.server.controller.js
modules/users/tests/server/user.server.routes.tests.js

The new WiredTiger engine is introduced in MongoDB 3.2.
It changes the output errmsg format for violation of unique index.
This commit adds support for the new format.
Fixes #1245

fix(core): Support WiredTiger engine errmsg format in MongoDB 3.2

---

gulpfile.js

`gulpfile.js` had an handled error, or more precisely handled but the actual error wasn't printed to the screen.

fix(gulp): unhandled error (not printed for the user)

---

package.json

Upgrades the Mongoose version to 4.4.8.
The need to limit Mongoose version to be less than 4.4.7 is no longer necessary due to a bug fix released with 4.4.8.
See ref: https://github.com/Automattic/mongoose/issues/3972
Resolves the need for #1264

fix(dependency): Bump Mongoose to 4.4.8

---

Dockerfile
docker-compose.yml

updating the Dockerfile and docker-compose.yml for up to date versions of MEAN.JS development environment
Fixes https://github.com/meanjs/mean/issues/1067

fix(docker): updating the Dockerfile and docker-compose.yml

---

gulpfile.js
package.json

Fixes #1251 - see the issue for motivation and other details

fix(gulp): replacing gulp-cssmin which has been deprecated and un-maintained with gulp-csso

---

gulpfile.js
package.json

The test:server:watch Gulp task has a parameter `onlyChanged` that is used to specify that if a server test file was modified, then only run that test suite. This removes the parameter, and sets the task behavior to the aforementioned.
Closes #1297

feat(gulp): test:server:watch task onlyChanged

---

gulpfile.js

Removes the trailing spaces in the gulpfile causing a linting error.

fix(gulp): Trailing spaces lint error in gulpfile

---

docker-compose.yml

Persisting the container names for the docker containers that get created allows to easily use an alias instead of the container id which is automatically generated and is usually different.

feat(docker): persisting the container names

---

config/env/default.js

Removing HSTSconfiguration set on lusca's csrf settings ut is already configured and provided using helmet
Fixes #1308

fix(hsts): removing HSTS configuration set on lusca's csrf settings

---

modules/core/client/css/core.css
modules/core/server/views/layout.server.view.html

Revert "Enhancement(core):Relative position attribute added to the header."

---

UPGRADE.md
gulpfile.js
modules/users/server/config/strategies/github.js
modules/users/server/models/user.server.model.js
modules/users/tests/server/user.server.model.tests.js
scripts/upgrade-users-sparse-index.js

Fixes an issue with an empty/missing/null Email coming from GitHub's
OAuth call response.
Also, introduces the `sparse` index option on the User model's Email
field. This will ensure that we can have multiple User documents without
the Email field.
Related #1145

fix(users): GitHub strategy missing email

---

modules/users/client/controllers/settings/edit-profile.client.controller.js

Updated edit profile controller to use the users service correctly. Edit profile now working. Closes #1282.

fix(users): Incorrect UsersService injection

---

.travis.yml

Add Node v6 to Travis CI, but let it fail.

feat(CI): Add Node v6 to Travis CI + remove V5 from allow_failures

---

README.md

I think the author meant to write "using *the* `wget` command," instead of 
"using `wget` command."

doc(getting started): Add missing word

---

modules/core/client/directives/page-title.client.directives.js

fix typo in modules/core/client/directives/page-title.client.directives.js
Fixes #1332

fix(core): Typo in page-title.client.directives.js

---

config/env/development.js
config/env/production.js
config/env/test.js
config/lib/express.js
config/lib/logger.js
modules/core/tests/server/core.server.config.tests.js
package.json

Fixes #1285 
Replacing file-stream-rotator with a better logging mechanism using winston which can be extended later for other use cases and integrations
`file-stream-rotator` has been deprecated, no longer maintained and right now pose a security vulnerability for the MEAN.JS project.
This PR
* adds `winston` as the logging mechanism which can be built upon for further and better log management in future refactoring and features.
* essentially deprecates the log options for now:
```js
log: {
// logging with Morgan - https://github.com/expressjs/morgan
// Can specify one of 'combined', 'common', 'dev', 'short', 'tiny'
format: 'dev',
options: {
// Stream defaults to process.stdout
// Uncomment/comment to toggle the logging to a log on the file system
// stream: {
//  directoryPath: …
```

replacing file-stream-rotator with winston

---

config/env/production.js
config/lib/socket.io.js

Supporting a certificate authority bundle file for the secured SSL configuration.
Supersedes https://github.com/meanjs/mean/pull/1189

Supporting a certificate authority bundle file for the secured SSL configuration.

---

.editorconfig

Fix Editorconfig file path patterns.
Editroconfig doesn't support patterns like `[**.js, **.json]`. Pattern `[**.{js,json}]` should be used instead as specified in [editorconfig](http://editorconfig.org/#wildcards)

Fix(editorconfig): Fix file path patterns

---

README.md

From [issue #1364](https://github.com/meanjs/mean/issues/1364)
The company renamed itself to mLabs, and the module name changed with it.

Documentation fix for Pivotal Web Services

---

modules/users/tests/client/edit-profile.client.controller.tests.js

Adds client-side tests for the Users Edit Profile client controller.
1) should have user context
2) should update the user profile
3) should set vm.error if error
Related #1283

feat(users): Edit Profile client controller tests

---

.bowerrc
package.json

Replace variety of gulp/grunt/sh/npm commands with npm commands.
Todo:
See #1258 for discussion.

[WIP] feat(core): use npm commands

---

modules/articles/client/controllers/articles.client.controller.js
modules/articles/client/services/articles.client.service.js

Extends the ArticlesService $resource object to include a custom method for creating, or updating, an Article instance.
Related #1260

feat(articles): ArticlesService extended $resource

---

README.md
package.json

feat(gulp): updating the README.md instructions with the changes to gulp being the mainstream vs the deprecation of grunt. Also added gulp as a task runner for freely executing tasks through running `npm` commands
Follow-up for #1296

Enhancement: Deprecating Grunt in favor of Gulp and NPM commands

---

Dockerfile
Procfile
package.json

cleaning up project dependencies by removing the forever package which is only really used by Heroku's
procfile to start up the node service

feat(forever): removing forever dependency

---

modules/core/client/services/menu.client.service.js
modules/core/client/views/header.client.view.html
modules/core/tests/client/menus.client.service.tests.js

feat(core): Add support for params in menu items 
Proposed by @scfox
Fixes #1304

Add support for params in menu items 

---

modules/articles/client/articles.client.module.js
modules/articles/client/config/articles-admin.client.config.js
modules/articles/client/config/articles-admin.client.routes.js
modules/articles/client/config/articles.client.menus.js
modules/articles/client/config/articles.client.routes.js
modules/articles/client/controllers/admin/article.client.controller.js
modules/articles/client/controllers/admin/list-articles.client.controller.js
modules/articles/client/controllers/articles.client.controller.js
modules/articles/client/views/admin/form-article.client.view.html
modules/articles/client/views/admin/list-articles.client.view.html
modules/articles/client/views/list-articles.client.view.html
modules/articles/client/views/view-article.client.view.html
modules/articles/server/policies/articles.server.policy.js
modules/articles/tests/client/admin.articles.client.controller.tests.js
modules/articles/tests/client/admin.articles.client.routes.tests.js
modules/articles/tests/client/admin.list.articles.client.controller.tests.js
modules/articles/tests/client/articles.client.routes.tests.js
modules/articles/tests/server/admin.article.server.routes.tests.js
modules/articles/tests/server/article.server.routes.tests.js

This is a work in progress, but is intended to gather feedback. There has been talk of separating the Articles views between authenticated User's and non-authenticated *Guests*. This is an attempt to explore going down this road. However, it turned into more of a *Public* states exploration :) 
I know there is competing changes to the Menu' service; #780 . I feel like the `shouldRender` method has been batted around lately. Once we determine how to proceed with implementing these desired features, I will adjust this PR to reflect the solution to the Menu's service refactoring. I think the difficulty in working with the `shouldRender` with these types of modifications, again shows the need for refactoring the Menu service.
@rhutchison @codydaig @trainerbill What do y'all think of this …

Articles admin feature

---

config/env/default.js
config/lib/express.js

Updating express session name variable from `key` which is deprecated to the new variable name `name`

Refactoring for express-session deprecated options

---

config/env/development.js
config/env/production.js
config/env/test.js

Updating environment variable name for mongodb with the new one for Heroku (according to https://devcenter.heroku.com/articles/mongolab)
Fixes #1411

Updating environment variable name for mongodb with the new one for Heroku

---

modules/chat/server/sockets/chat.server.socket.config.js

In the chat example, the profileImageURL is not sent to clients when a user disconnects.
Before:
After:

fix(chat): fixed profile image not displaying properly on disconnect

---

docker-compose.yml

feat(deploy) Add data container for docker-compose and update to docker compose version 2.
Add data container for mongodb
Add data container for web data
Update to compose version 2
Use networking of compose version 2 (remove links)
Use depends_on for containers
Fixes #1434

Add data container for docker-compose and update to docker compose version 2

---

Dockerfile-production
README.md
docker-compose-production.yml

feat(deploy) Add dockerfile and compose for production.
Add Dockerfile for production (#1431)
Add docker-compose.yml for production
Update documentation for deployment
Fixes #1435
Fixes #1431

Add dockerfile and compose for production

---

bower.json
config/assets/default.js
modules/core/client/app/config.js
modules/users/client/controllers/settings/change-profile-picture.client.controller.js
modules/users/client/css/users.css
modules/users/client/views/settings/change-profile-picture.client.view.html

feat(users): Profile picture cropping, mobile uploading and progress bar
Improvements to the Change Profile Picture page including:
- The option to take a camera pic and upload it is now offered on mobile
- Large images (such as those taken from a camera) no longer crash the page
- Add ability to crop pictures using [ngImgCrop](https://github.com/alexk111/ngImgCrop)
- Add progress bar during uploading
- Large images are now properly resized to thumbnails
- Much of this was accomplished by switching from the [angular-file-upload](https://github.com/nervgh/angular-file-upload) 
module to the far more fully-featured and frequently-updated [ng-file-upload](https://github.com/danialfarid/ng-file-upload)

feat(users): Profile picture cropping, mobile uploading and progress bar

---

modules/users/server/models/user.server.model.js

Fixes Node v6 crypto deprecation warning  `crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest`

fix(users): specify a digest with crypto.pbkdf2Sync

---

modules/articles/client/config/articles-admin.client.routes.js
modules/articles/client/controllers/admin/article.client.controller.js
modules/articles/client/controllers/admin/list-articles.client.controller.js
modules/articles/tests/client/admin.articles.client.controller.tests.js
modules/articles/tests/client/admin.articles.client.routes.tests.js
modules/articles/tests/client/admin.list.articles.client.controller.tests.js

Fixes the naming conflicts for the Articles controllers.
Due to how Angular injects the controllers into the StateProvider,
naming conflicts were caused between the Articles public & admin module
controllers.
To resolve the issue the referenced controllers in the Articles admin
route configurations must be unique, and match up with the Admin
controllers.

fix(articles): Article controllers name conflicts

---

config/lib/app.js

Remove unused `loadModels()` from app.js, as it doesn't seem to be used anywhere.
— or am I missing something?
It was added here: https://github.com/meanjs/mean/commit/edb62344bc4af3cb28c3469dc7463c13a2fc76a1

Fix(server): Remove unused loadModels()

---

modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/tests/server/user.server.routes.tests.js

Avoid updating secure fields as password, salt ..etc through
user profile update.
Fixes #1420

Fix(users): Don't update secure profile fields

---

config/lib/express.js
modules/core/client/app/config.js
modules/core/client/app/init.js
modules/core/server/views/layout.server.view.html
modules/core/tests/server/core.server.config.tests.js

Disable Angular debug data in production for a significant performance boost.
Passes environment variable from template to app config and from there to Angular bootstrap config.
https://docs.angularjs.org/guide/production#disabling-debug-data
See #1294

feat(core): disable Angular debug data in production

---

README.md
package.json

Removes deprecated `onlyChanged` npm script. Watch now always runs only changed tests, no parameter needed.
Change to gulp tasks was in this commit: https://github.com/meanjs/mean/commit/eaead7a30cb2a60ad25250940e79b42619261e23

fix(core): Update npm commands and documentation

---

.travis.yml

Remove Node.js v6 from `allow_failures` matrix at Travis config.
Seems to be passing anyway and v6 is already production ready.

feat(build): Modify Travis config

---

modules/users/server/controllers/admin.server.controller.js
modules/users/server/controllers/users/users.profile.server.controller.js

feat(users): Routes are currently leaking access tokens
Authentication routes use route /api/users/me and /api/users/ (for admins). Maybe a mock closer to passport like: https://gist.github.com/mweibel/5219403 would be nice. In the meanwhile this should make the returned user object safer. See:
https://www.facebook.com/FacebookforDevelopers/videos/10152795636318553/
(specifically the part about stealing access tokens). I re-used code from core:
modules/core/server/controllers/core.server.controller.js
Fixes n/a - general security improvement

Sanitise user

---

config/config.js
config/env/default.js
config/lib/express.js
modules/users/server/controllers/users/users.password.server.controller.js

Generic DOMAI configuration environment variable, useful for setting links to an app
in reset email templates, and other cases.
Fixes #871 and #847

Adds a generic DOMAIN configuration environment

---

modules/users/client/css/users.css
modules/users/client/views/authentication/authentication.client.view.html
modules/users/client/views/authentication/signin.client.view.html
modules/users/client/views/settings/manage-social-accounts.client.view.html

feat(users): Improved social login buttons UI
All social buttons are now responsive and display properly on mobile
The grid is not broken if one is removed
Cleaned up redundant CSS

feat(users) Improved social login buttons UI

---

.travis.yml
config/env/test.js
gulpfile.js
karma.conf.js
package.json

fix(tests): Reorganized coverage tests
Moved coverage configuration from karma.conf to the gulpfile:
- The server-side coverage tests are already configured in the gulpfile so I think the client-side ones should be too, cleaning up the karma.conf file.
- The previous method to tell karma to run coverage tests involved flipping an environment variable which karma.conf then read. I suspect that this is what caused client-side Travis builds not to send reports to coveralls
LCOV report file concatenation and sending to coveralls has been moved from the gulpfile to .travis.yml, as per @mleanos [suggestion](https://github.com/meanjs/mean/commit/7be191042066e58850899000ee02b6557d744c18#commitcomment-18891729)
- Now coverage tests can be run locally using gulp test:coverage without error if you …

fix(tests): Reorganized coverage tests

---

Dockerfile-production

Gulp actually requires the gulp package and it's libraries to be installed, and this goes even if gulp or gulp-cli are installed globally. This is why the build fails.
The fix in this PR mitigates this by updating the Dockerfile-production to hint npm to install all dependencies.
Fixes #1453

Updating the dockerfile-production to build with gulp support

---

modules/chat/client/css/chat.css
modules/core/client/css/core.css
modules/users/client/css/users.css

Fixes css lint warnings of properties not alphabetized.

fix(lint): CSS alphabetize warnings

---

modules/core/client/config/core.client.route-filter.js

feat(users): Redirect to login page rather than 403 if not signed in
Non-signed in users are being redirected to the unfriendly 403 forbidden page instead of the sign in page as should be the case. Fixed the tiny bug in the code that caused this to happen.

fix(core): Redirect to login page rather than 403 if not signed in

---

modules/users/client/controllers/authentication.client.controller.js
modules/users/client/controllers/password.client.controller.js
modules/users/client/controllers/settings/change-password.client.controller.js
modules/users/client/controllers/settings/manage-social-accounts.client.controller.js
modules/users/client/services/users.client.service.js
modules/users/tests/client/authentication.client.controller.tests.js
modules/users/tests/client/password.client.controller.tests.js

Replaces the $http service calls with promise based methods of the client-side UsersService for the following:
Users Change Password
Users Manage Social Accounts
Users Password Forgot
Users Password Reset
Users Signup
Users Signin
Modifies tests to reflect changes.
Closes #1479

Deprecated $http success/error promise methods

---

config/lib/logger.js

Cleaning up unused parameters in logger setup

---

modules/users/client/controllers/admin/user.client.controller.js
modules/users/client/views/admin/view-user.client.view.html

fix(user): hide delete button for self
Remove delete button for self
Fixes #1531

fix(user): hide delete button for self

---

modules/users/client/views/settings/manage-social-accounts.client.view.html

fix(user): remove bad request for local.png
Removes a bad image request from manage social account settings page
#1537 with suggestions from @mleanos
Fixes #1537

fix(user): remove bad request for local.png

---

modules/articles/tests/server/admin.article.server.routes.tests.js
modules/articles/tests/server/article.server.routes.tests.js
modules/users/client/views/authentication/signin.client.view.html
modules/users/server/config/strategies/local.js
modules/users/tests/client/authentication.client.controller.tests.js
modules/users/tests/e2e/users.e2e.tests.js
modules/users/tests/server/user.server.routes.tests.js

It's quite boring to force your users to remember the username they've created in your app to signin. So I've made an option to put an email or username. It's far more interesting to user experience, and a lot of applications are doing that, eg. Snapchat.

feat(users): change username to usernameOrEmail in signin

---

config/assets/production.js
config/lib/express.js
gulpfile.js
package.json

feat(core): Add prod asset versioning
Asset versioning for prod - idea from #1509
Fixes #1509

feat(core): Add prod asset versioning

---

Dockerfile
Dockerfile-production
config/assets/default.js
package.json

@sujeethk Just leftover. I must have missed them in the rebase. Thanks for catching that!

grunt(core): Remove Excess Grunt Dependencies

---

modules/core/client/config/core.client.route-filter.js
modules/core/client/config/core.client.routes.js
modules/core/client/controllers/error.client.controller.js
modules/core/client/services/interceptors/auth-interceptor.client.service.js
modules/core/client/views/400.client.view.html
modules/core/client/views/403.client.view.html
modules/core/client/views/404.client.view.html
modules/users/server/controllers/users/users.authentication.server.controller.js

Supersedes #1510 
Other than the work put into this by @hyperreality, this PR adds:
Changed the error responses returned from the Sign Up & Sign In API
calls to use 422 rather than 400.
For insight into why this change was made:
https://github.com/meanjs/mean/pull/1510#issuecomment-247435378
For reference on why to use 422 over 400:
https://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm
Fixes #1504

fix(core): Add custom 400 and 404 error messages

---

modules/articles/server/controllers/articles.server.controller.js
modules/articles/tests/server/admin.article.server.routes.tests.js
modules/users/server/controllers/admin.server.controller.js
modules/users/server/controllers/users/users.authentication.server.controller.js
modules/users/server/controllers/users/users.password.server.controller.js
modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/tests/server/user.server.routes.tests.js

Fixes incorrect usage of 400 HTTP responses being returned from the server, in favor of using 422.
Also, changed a couple return codes to 401 where it was more appropriate.
See this article for reasoning behind moving to 422, and why 400 isn't appropriate for these cases.
https://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm
Reference:
https://github.com/meanjs/mean/commit/6be12f8a061a2f7228e254c314a46ad7a78966d1
Related:
https://github.com/meanjs/mean/pull/1547
https://github.com/meanjs/mean/pull/1510

fix(express): Incorrest uses of 400 error codes

---

modules/core/client/services/interceptors/auth-interceptor.client.service.js
modules/core/tests/client/interceptors/auth-interceptor.client.tests.js

feat(core): Add error handler for failed requests
Add error handle for failed requests(no response from server)
Using Notification.error to show error message
Added test for the notification in Auth Interceptor
Fixes #1556

feat(core): Add error handler for failed requests

---

modules/articles/client/config/articles-admin.client.routes.js
modules/articles/client/config/articles.client.routes.js
modules/articles/client/services/articles.client.service.js
modules/articles/tests/client/admin.articles.client.controller.tests.js
modules/articles/tests/client/admin.articles.client.routes.tests.js
modules/articles/tests/client/admin.list.articles.client.controller.tests.js
modules/articles/tests/client/articles.client.routes.tests.js
modules/articles/tests/client/list-articles.client.controller.tests.js
modules/chat/client/config/chat.client.routes.js
modules/chat/client/views/chat.client.view.html
modules/chat/tests/client/chat.client.controller.tests.js
modules/chat/tests/client/chat.client.routes.tests.js
modules/core/client/app/init.js
modules/core/client/config/core.client.routes.js
modules/core/client/views/header.client.view.html
modules/core/client/views/home.client.view.html
modules/core/server/views/layout.server.view.html
modules/users/client/config/users-admin.client.routes.js
modules/users/client/config/users.client.routes.js
modules/users/client/controllers/settings/change-profile-picture.client.controller.js
modules/users/client/services/users.client.service.js
modules/users/client/views/settings/change-profile-picture.client.view.html
modules/users/tests/client/authentication.client.controller.tests.js
modules/users/tests/client/edit-profile.client.controller.tests.js
modules/users/tests/client/password.client.controller.tests.js
modules/users/tests/client/users-admin.client.routes.tests.js
modules/users/tests/client/users.client.routes.tests.js

@0x24a537r9
>Fixes #1224. Everything looks good in the browser and server/e2e tests, but unfortunately the unit tests are broken, and I'll probably need some guidance from someone more familiar with Angular/Karma.
This is a continuation of #1230, in an attempt to finalize the changes by fixing the broken tests.
NOTE: The fixes to the client-side tests aren't ideal. At the moment, they will suffice. [This comment](https://github.com/angular-ui/ui-router/issues/212#issuecomment-60803437),
among others in that issue, led me to choose this method as the fix to
avoid having to change any core code.

fix(core): Remove the <base> tag (continues #1230)

---

.eslintrc.js
package.json

This PR supersedes https://github.com/meanjs/mean/pull/1414 and updates core node package engine (including es5 support for eslint configuration), as well as adding a `cleanup` and `reinstall` npm shortcut scripts.

Node engine updates and package.json additional scripts

---

config/env/default.js

Removes the dangling comma from the default configuration db.promise
setting. This was causing a lint error.

fix(config): Default config dangling comma

---

config/env/development.js
config/env/production.js
config/env/test.js
config/lib/express.js
modules/core/server/views/layout.server.view.html

fix(core): fix twitter meta tags
I believe the Twitter meta tags are outdated and this PR fixes them.
Taking into account the current MEAN.js tags and the Twitter docs, the most similar feature I found
is the Twitter Summary Card (https://dev.twitter.com/cards/types/summary), which requires 2 tags that currently do not exist (twitter:card and twitter:site) and there's another one already implemented in MEAN.js which is not referenced in Twitter docs (twitter:url).

fix(core): fix twitter meta tags

---

modules/users/client/controllers/settings/manage-social-accounts.client.controller.js
modules/users/client/views/settings/manage-social-accounts.client.view.html
modules/users/server/controllers/users/users.authentication.server.controller.js

fix(users): fix redirect when signup or add provider

---

config/env/default.js
config/env/development.js
config/env/production.js
config/env/test.js
modules/core/tests/server/core.server.config.tests.js
modules/users/client/controllers/authentication.client.controller.js
modules/users/client/views/authentication/signup.client.view.html
modules/users/server/models/user.server.model.js
modules/users/tests/e2e/users.e2e.tests.js
modules/users/tests/server/user.server.model.tests.js

feat(user): add strict validations for username
Idea proposed by @sparshy #1204
Suggestions, rules and tests from Trustroots @simison
Added validations on user server model
Added relevant tests on user server tests
Fixes #1204

feat(user): add strict validations for username

---

.travis.yml

NodeJS v7 is out: https://nodejs.org/en/blog/release/v7.0.0/

feat(ci): Test for NodeJS v7 (allow failure)

---

.gitignore
config/assets/default.js
gulpfile.js

Compiling `sass/less` files to `<module>/client/css` directory makes it difficult to differentiate between compiled and raw css files.
By compiling them to appropriate directories, compiled files can be easily ignored.

feat(build): Ignore compiled sass/less files from git

---

config/env/default.js

Fixes linting errors thrown from incorrect spacing in the default environment config. Incorrect spacing at the `illegalUsernames` config setting.

fix(config): Default env config lint error

---

config/assets/production.js

Removed the ng-img-crop references from the production assets
configuration, since the library has been removed from the project.
Also, re-ordered the CSS section to be in alphabetical order.

Incorrect production assets

---

config/lib/mongoose.js

If no promises library set correctly for the mongoose.Promise property then the following warning notice is omitted by mongoose:
`DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html`

fix(mongoose): fixing mongoose deprecation notice for promises lib

---

server/config/lib/mongoose.js

If no promises library set correctly for the mongoose.Promise property then the following warning notice is omitted by mongoose: `DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html`

[v2] MEAN.JS API - fix(mongoose): fixing mongoose deprecation notice for promises

---

server/gulpfile.js
server/package.json

* fixing `npm start` to work with the --harmony flag
* fixing debug task to actually use --debug and --inspect in the new v8

[v2] - MEAN.JS API - fix(debug): fixing gulp node debug task

---

gulpfile.js
package.json

Deprecates the node-inspector package and relies on native Node.js support for the --debug option which is available since 6.3, and uses the --inspect flag which replaces --debug from v7 and on
Fixes issues reported in #1738 #1735 #1722

Deprecating node-inspector infavor of native nodejs debug

---

modules/core/tests/server/core.server.config.tests.js
package.json

mock-fs will override node's core fs calls which mess up the tests.

Removing unused mock-fs library which caused tests to fail

---

.travis.yml

Ever since we moved out to node-sass we shouldn't really have any dependencies on ruby gemfiles

build(gems): we shouldnt need any gem file installations anymore

---

modules/articles/tests/server/article.server.routes.tests.js

feat(articles): Simple test enhancement
Simple test enhancement proposed by @jrodenbostel.  Eases troubleshooting when Article save fails during test execution.
Further reference here: https://github.com/meanjs/generator-meanjs/pull/257
Fixes #1658

feat(articles): Simple test enhancement

---

.travis.yml
package.json
protractor.conf.js

Fixes an issue with the Travis CI builds failing at the E2E tests due to
an apparent issue with the Mozilla Gecko web-driver used with Selenium.
1) Upgrades `gulp-protractor` to ensure Protractor v5> is used.
2) Removes `--firefox` option from the Travis CI Selenium
`webdriver-manager update` step.
3) Changes Protractor config to use Chrome instead of Firefox.
**NOTE:** This PR was originally created on a debugging branch to determine the issues with the E2E tests running on Travis CI builds. The below conversation will reflect the process of numerous experimental commits to track down the source of the issues. After a conclusion was made, the commits in this branch were squashed, and the commit details were changed here.

fix(build): E2E coverage broken on Travis CI

---

config/lib/express.js

Fixes a trailing space eslint error in the Express config.

fix(build): ESLint error in Express config

---

.travis.yml

I felt like leaving these just uncommented so it helps in future when people want to add new versions here.
I can also remove them completely (or remove only `allow_failures`) if you think it's better.

feat(Travis): Don't allow Node.js 8 testing fail

---

karma.conf.js
package.json

Makes writing and debugging tests with Karma so much easier.
Looks like this:
Instead of this:
My only worry would be that I don't know how well it will be maintained, but on the other hand reversing is no-brainer.

feat(Karma): Add mocha style progress to Karma tests

---

gulpfile.js

fix(gulpfile): Update templateCache root path
In the production build `application-xxx.min.js`, the url of the mark up being put into `$templateCache` is incorrect, the `/` is missing.
Although the mark-ups are already put into `$templateCache`, the browser will still fetch the templates files when they are needed.
Fixes #1820

fix(gulpfile): Update templateCache root path

---

config/env/development.js
config/env/local.example.js
config/env/production.js
config/env/test.js
config/lib/app.js
config/lib/express.js
config/lib/mongoose.js
config/lib/socket.io.js
gulpfile.js
modules/articles/server/config/articles.server.config.js
modules/articles/tests/server/admin.article.server.routes.tests.js
modules/articles/tests/server/article.server.routes.tests.js
modules/core/tests/server/core.server.config.tests.js
modules/users/server/config/users.server.config.js
modules/users/tests/server/user.server.routes.tests.js
package.json

Upgrades Mongoose to ~~4.11.1~~ 4.11.3
Updates Mongoose connection implementation to accommodate deprecated
features & connection options.
Also, updates the Gulp Mocha tasks to reflect changes to the Mongoose
implementation.
Fixes tests to get the database from the existing Mongoose singleton.
Derives from changes in https://github.com/meanjs/mean/pull/1816
Closes https://github.com/meanjs/mean/issues/1814

feat(config): Mongoose 4.11 upgrade

---

modules/users/client/views/password/forgot-password.client.view.html
modules/users/server/controllers/users/users.password.server.controller.js
modules/users/tests/server/user.server.routes.tests.js

Adds support for recovering your account using email. Previously this would work only with username. Now both are supported.
Breaking change to API (`username` field changed to `userhandle`), but it's really simple to fix if anyone out there is relying on that e.g. with their mobile apps.
Resolves #1833

feat(user): Add email support to forgot password

---

gulpfile.js

Pass the path string of the changed file to gulp-refresh plugin,
so that an exception won't be thrown when test files are reloaded
Fixes #1840

fix(gulp): test:server:watch broken task

---

gulpfile.js

Previously this might've caused issues with AngularJS, but since we are now using ngAnnotate, those issues are gone.
Minified files will be quite a lot smaller with this option.
I did some manual clicking around and seemed working fine.
https://github.com/mishoo/UglifyJS2#minify-options
Closes #1599

feat(build): Turn on mangling for uglify

---

modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/tests/server/user.server.routes.tests.js

Silently fails when existing file didn't exist when unlinking it.
Fixes #1778

fix(users): don't fail on missing old image on image upload

---

package.json

`crypto` is now part of NodeJS core: https://www.npmjs.com/package/crypto

Remove deprecated crypto package

---

config/env/production.js

Updating SSL connection settings to be in-par with new versions of Mongoose.
Related issue: https://github.com/meanjs/mean/commit/c0f6cb3e4d1a2cf5d1540643f3ce79934f5d957b#commitcomment-22974350

fix(mongodb): update ssl connection settings

---

.eslintrc.js
config/lib/logger.js
gulpfile.js
modules/articles/client/controllers/admin/article.client.controller.js
modules/core/client/app/config.js
modules/core/client/config/core.client.routes.js
modules/core/client/directives/auto-focus.client.directive.js
modules/core/client/directives/page-title.client.directive.js
modules/core/client/services/menu.client.service.js
modules/core/tests/client/interceptors/auth-interceptor.client.tests.js
modules/core/tests/client/menus.client.service.tests.js
modules/core/tests/client/socket.io.client.service.tests.js
modules/core/tests/server/core.server.config.tests.js
modules/users/server/controllers/users/users.profile.server.controller.js
modules/users/server/models/user.server.model.js
modules/users/tests/client/password-validator.client.directive.tests.js
modules/users/tests/client/password-verify.client.directive.tests.js
modules/users/tests/client/password.client.controller.tests.js
modules/users/tests/e2e/users.e2e.tests.js
modules/users/tests/server/user.server.model.tests.js
modules/users/tests/server/user.server.routes.tests.js

Defines `space-before-function-paren` eslint rule and changes files accordingly.
Resolves #1605

fix(eslint): Inconsistent spacing before function parentheses

---

.travis.yml

Travis is randomly failing at:
```
[08:34:29] I/launcher - Running 1 instances of WebDriver
[08:34:29] E/local - Error code: 135
[08:34:29] E/local - Error message: No update-config.json found. Run 'webdriver-manager update' to download binaries.
[08:34:29] E/local - Error: No update-config.json found. Run 'webdriver-manager update' to download binaries.
```
So let's see if this helps.

fix(travis): Fix Travis failing on webdriver issues

---

.eslintrc.js

Fixes eslint errors in eslint 4.x:
```
Linter] Error running ESLint Error: /mean/.eslintrc.js:
Configuration for rule "space-before-function-paren" is invalid:
Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
```
We're still in eslint 2.x. so apparently no problems as of yet, but will have to be fixed before updating eslint (#1846).
Related to previous PR #1844 and already closed issue #1605

fix(eslint): Make `space-before-function-paren` rule consistent with other rules

---

README.md
config/env/default.js
modules/core/client/views/header.client.view.html
modules/users/client/views/settings/change-profile-picture.client.view.html
modules/users/server/controllers/users/users.profile.server.controller.js
package.json

This PR aimed to save profile images to a S3 Bucket.
I discovered that deploying to Heroku leaded to profile images not being saved.
This 3 environment parameters need to be filled:
S3_PROFILE_BUCKET: the name of the bucket where the images will be saved
S3_ACCESS_KEY_ID: Your S3 access key
S3_SECRET_ACCESS_KEY: Your S3 access key password

Save profile images to Amazon S3

---

modules/articles/client/views/admin/list-articles.client.view.html

fix(articles) Alert missing.
In the Admin - 'manage articles' view, if there are no articles yet there's supposed to be an alert.
However, it doesn't show up.
Fixes #1930

Manage articles - no articles alert missing.

---

modules/articles/client/views/admin/list-articles.client.view.html

fix(articles): Updated warning message condition
In the Admin - 'manage articles' view, the warning message will be displayed only when there is no article present.
Fixes #1930 ,Fixes #1933

Manage Article - Updating the warning message condition

---

.vscode/launch.json

Adds configuration for vscode:
- Adds most gulp tasks
- Adds chrome debugging: Debug client-side within vscode
- Adds debug attach: Debug server-side within vscode
- Adds compound tasks to start multiple combos of the above

feat (ide) Add vscode launch config

---

modules/core/client/views/home.client.view.html

This PR does the following:
- When possible, use the https version of the urls
- Removed one dead SO link regarding Express
- Added `rel="noopener"` in links using `target="_blank"`
More info about the use of `rel="noopener"` for security reasons:
https://developers.google.com/web/tools/lighthouse/audits/noopener
https://mathiasbynens.github.io/rel-noopener/
I understand that this view just has generic content which is meant to be replaced but still it's good to have this covered :)

feat(core): Improve links in home view

---

gulpfile.js
modules/core/tests/client/menus.client.service.tests.js
modules/users/tests/e2e/users.e2e.tests.js
package-lock.json
package.json
protractor.conf.js

Fixes Gulp task issues after upgrading to Gulp v4.
Disables two E2E tests that are failing for unknown reasons.
Upgrades gulp-protractor to 4.1.0
FIxes protractor config "specs" setting to match environment assets configuration.
Fixes #2004

fix(gulp): Gulp tasks broken after Gulp v4 upgrade

---

gulpfile.js

Fixes an issue with the "defualt" & "build" Gulp tasks that override the current NODE_ENV. These two tasks should inherit the NODE_ENV that has been set.
Also, updates the "prod" Gulp task to ensure the NODE_ENV is set to "prod" before the "build" task is run.

fix(gulp): Gulp tasks overriding NODE_ENV
